<a href="https://colab.research.google.com/github/davidlealo/sic_ia_2026/blob/main/ejercicios_profesor/sic2026_ia_clase03_cap5_grupos_PROFESOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Carga de datos

from sklearn.datasets import load_iris
data = load_iris()

# EDA
data # Revisar los datos

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
import pandas as pd

# Convertir el dataset de scikit-learn a un DataFrame de pandas
df = pd.DataFrame(data.data, columns=data.feature_names)

# Agregar la columna objetivo (target)
df['target'] = data.target

# Mostrar las primeras filas
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Info de df

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [ ]:
# Revisar si hay datos nulos

df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [ ]:
import seaborn as sns

# Cargar el dataset mpg en un DataFrame de pandas
mpg = sns.load_dataset('mpg')

# Ver las primeras filas
print(mpg.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [ ]:
# Sumar valores únicos

print(mpg['model_year'].value_counts())

model_year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

In [ ]:
# Sumar valores únicos

print(mpg['origin'].value_counts())

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [ ]:
# Sumar valores únicos

print(mpg['name'].value_counts())

name
ford pinto             6
ford maverick          5
amc matador            5
toyota corolla         5
amc hornet             4
                      ..
amc concord dl         1
volkswagen rabbit l    1
mazda glc custom l     1
mazda glc custom       1
chevy s-10             1
Name: count, Length: 305, dtype: int64

In [ ]:
mpg["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [ ]:
print(mpg['displacement'].value_counts())

displacement
97.0     21
350.0    18
98.0     18
318.0    17
250.0    17
         ..
81.0      1
100.0     1
145.0     1
181.0     1
144.0     1
Name: count, Length: 82, dtype: int64

In [ ]:
mpg["displacement"].unique()

array([307. , 350. , 318. , 304. , 302. , 429. , 454. , 440. , 455. ,
       390. , 383. , 340. , 400. , 113. , 198. , 199. , 200. ,  97. ,
       110. , 107. , 104. , 121. , 360. , 140. ,  98. , 232. , 225. ,
       250. , 351. , 258. , 122. , 116. ,  79. ,  88. ,  71. ,  72. ,
        91. ,  97.5,  70. , 120. ,  96. , 108. , 155. ,  68. , 114. ,
       156. ,  76. ,  83. ,  90. , 231. , 262. , 134. , 119. , 171. ,
       115. , 101. , 305. ,  85. , 130. , 168. , 111. , 260. , 151. ,
       146. ,  80. ,  78. , 105. , 131. , 163. ,  89. , 267. ,  86. ,
       183. , 141. , 173. , 135. ,  81. , 100. , 145. , 112. , 181. ,
       144. ])

In [ ]:
mpg["cylinders"].unique()

array([8, 4, 6, 3, 5])

In [ ]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

# Escalamiento y normalización de datos en scikit-learn

## 1. Por qué escalar los datos

Muchas variables de un dataset están en escalas muy distintas. Por ejemplo, la edad de una persona puede ir de 18 a 90, mientras que su ingreso anual puede ir de 0 a 100.000.000. Varios algoritmos de aprendizaje automático son sensibles a estas diferencias:

- **Algoritmos basados en distancias** (KNN, K-Means, SVM con kernel RBF): una variable con valores grandes domina el cálculo de la distancia.
- **Algoritmos optimizados por gradiente** (regresión logística, redes neuronales, regresión lineal con descenso de gradiente): convergen más rápido y de forma más estable cuando las variables tienen escalas similares.
- **Modelos con regularización** (Ridge, Lasso, ElasticNet): la penalización afecta de forma desigual a coeficientes de variables en escalas distintas.
- **PCA**: busca direcciones de máxima varianza, por lo que una variable con varianza numéricamente grande domina los componentes.

En cambio, los **modelos basados en árboles** (árboles de decisión, Random Forest, Gradient Boosting, XGBoost) en general **no necesitan escalamiento**, porque dividen cada variable por umbrales y el orden de los valores no cambia al escalar.

Todos los escaladores de scikit-learn están en el módulo `sklearn.preprocessing` y comparten la misma interfaz:

| Método | Qué hace |
|---|---|
| `fit(X)` | Aprende los parámetros necesarios (media, mínimo, cuantiles, etc.) a partir de `X`. |
| `transform(X)` | Aplica la transformación usando los parámetros ya aprendidos. |
| `fit_transform(X)` | Hace ambas cosas en un solo paso (solo sobre datos de entrenamiento). |
| `inverse_transform(X)` | Revierte la transformación (disponible en la mayoría). |

---

## 2. StandardScaler

### Idea

Centra cada variable en media 0 y la escala para que tenga desviación estándar 1. Es la estandarización clásica o **z-score**.

### Fórmula

$$
z = \frac{x - \mu}{\sigma}
$$

donde $\mu$ es la media y $\sigma$ la desviación estándar de la columna, calculadas sobre el conjunto de entrenamiento.

### Ejemplo

```python
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1, 200],
              [2, 300],
              [3, 400]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(scaler.mean_)   # [  2. 300.]
print(scaler.scale_)  # [ 0.816  81.65]
print(X_scaled)
# [[-1.2247 -1.2247]
#  [ 0.      0.    ]
#  [ 1.2247  1.2247]]
```

### Características

- El resultado **no queda acotado** a un rango fijo.
- Es **sensible a outliers**, porque la media y la desviación estándar se ven afectadas por valores extremos.
- No cambia la forma de la distribución: si los datos eran asimétricos, siguen siéndolo.
- Parámetros útiles: `with_mean=False` (necesario para matrices dispersas) y `with_std=False`.

### Cuándo usarlo

Es la opción por defecto para la mayoría de los modelos lineales, SVM, redes neuronales y PCA, especialmente cuando los datos son aproximadamente normales y no hay outliers fuertes.

---

## 3. MinMaxScaler

### Idea

Lleva cada variable a un rango fijo, por defecto $[0, 1]$.

### Fórmula

$$
x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
$$

Para un rango general $[a, b]$:

$$
x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}} \cdot (b - a) + a
$$

### Ejemplo

```python
from sklearn.preprocessing import MinMaxScaler

X = np.array([[1, 200],
              [2, 300],
              [3, 400]])

scaler = MinMaxScaler()              # feature_range=(0, 1) por defecto
X_scaled = scaler.fit_transform(X)
print(X_scaled)
# [[0.  0. ]
#  [0.5 0.5]
#  [1.  1. ]]

scaler_2 = MinMaxScaler(feature_range=(-1, 1))
print(scaler_2.fit_transform(X))
# [[-1. -1.]
#  [ 0.  0.]
#  [ 1.  1.]]
```

### Características

- El resultado queda **acotado** al rango indicado (en los datos de entrenamiento).
- Es **muy sensible a outliers**: un solo valor extremo define el mínimo o el máximo y comprime todos los demás valores en una franja pequeña.
- Datos nuevos fuera del rango de entrenamiento pueden quedar fuera de $[0, 1]$. El parámetro `clip=True` los recorta al rango.
- Conserva la forma de la distribución y los ceros solo si el mínimo es 0.

### Cuándo usarlo

Cuando el algoritmo o el dominio requieren valores en un rango fijo: intensidades de píxeles en imágenes, entradas de redes neuronales con activaciones acotadas (sigmoide), o cuando se sabe que los datos tienen límites naturales y no hay outliers.

---

## 4. MaxAbsScaler

### Idea

Divide cada variable por su valor absoluto máximo, de modo que el resultado queda en $[-1, 1]$. **No centra** los datos.

### Fórmula

$$
x' = \frac{x}{\max(|x|)}
$$

### Ejemplo

```python
from sklearn.preprocessing import MaxAbsScaler

X = np.array([[ 1, -10],
              [ 2,   0],
              [-4,   5]])

scaler = MaxAbsScaler()
print(scaler.fit_transform(X))
# [[ 0.25 -1.  ]
#  [ 0.5   0.  ]
#  [-1.    0.5 ]]
```

### Características

- **Preserva los ceros** y el signo de los valores.
- Funciona directamente sobre **matrices dispersas** (`scipy.sparse`) sin destruir su dispersión.
- Es sensible a outliers, igual que MinMaxScaler.

### Cuándo usarlo

Con datos dispersos, por ejemplo matrices de conteo de palabras (bag of words, TF-IDF), donde centrar los datos convertiría millones de ceros en valores distintos de cero y haría explotar la memoria.

---

## 5. RobustScaler

### Idea

Similar a StandardScaler, pero usa estadísticos **robustos frente a outliers**: la mediana en lugar de la media y el rango intercuartílico (IQR) en lugar de la desviación estándar.

### Fórmula

$$
x' = \frac{x - \text{mediana}}{Q_3 - Q_1}
$$

donde $Q_1$ y $Q_3$ son los percentiles 25 y 75.

### Ejemplo

```python
from sklearn.preprocessing import RobustScaler

X = np.array([[1], [2], [3], [4], [1000]])   # 1000 es un outlier

print(StandardScaler().fit_transform(X).ravel())
# [-0.50 -0.50 -0.50 -0.50  2.00]   los valores normales quedan casi iguales

print(RobustScaler().fit_transform(X).ravel())
# [-1.  -0.5  0.   0.5 498.5]       los valores normales conservan su separación
```

### Características

- Los outliers **no afectan** el cálculo de los parámetros, por lo que la mayoría de los datos queda bien escalada.
- Los outliers **no se eliminan**: siguen presentes en el resultado con valores grandes.
- El resultado no queda acotado.
- Parámetros útiles: `quantile_range=(25.0, 75.0)` para cambiar los percentiles y `with_centering=False` para datos dispersos.

### Cuándo usarlo

Cuando el dataset contiene outliers que no se quieren o no se pueden eliminar, como ingresos, precios de viviendas o tiempos de respuesta.

---

## 6. Normalizer

### Idea

A diferencia de los anteriores, **trabaja por filas, no por columnas**. Escala cada muestra (fila) para que tenga norma 1.

### Fórmula (norma L2, por defecto)

$$
x'_i = \frac{x_i}{\sqrt{\sum_j x_{ij}^2}}
$$

También admite `norm='l1'` (suma de valores absolutos igual a 1) y `norm='max'`.

### Ejemplo

```python
from sklearn.preprocessing import Normalizer

X = np.array([[3, 4],
              [1, 0],
              [6, 8]])

print(Normalizer().fit_transform(X))
# [[0.6 0.8]
#  [1.  0. ]
#  [0.6 0.8]]   las filas 1 y 3 quedan iguales: solo importa la dirección
```

### Características

- No aprende nada en `fit` (cada fila se normaliza de forma independiente).
- Elimina la información de magnitud de cada muestra y conserva solo su dirección.

### Cuándo usarlo

Cuando lo relevante es la **proporción** entre variables y no su magnitud absoluta, por ejemplo en clasificación de textos con vectores TF-IDF o cuando se usa similitud coseno. **No reemplaza** a los escaladores por columna.

---

## 7. QuantileTransformer

### Idea

Transforma cada variable usando su función de distribución acumulada, de modo que el resultado siga una distribución **uniforme** en $[0, 1]$ o una distribución **normal**.

### Funcionamiento

1. Estima los cuantiles de cada columna (por defecto `n_quantiles=1000`).
2. Reemplaza cada valor por su posición relativa (rango percentil).
3. Si `output_distribution='normal'`, mapea esos percentiles a una normal estándar.

### Ejemplo

```python
from sklearn.preprocessing import QuantileTransformer

rng = np.random.RandomState(0)
X = rng.lognormal(size=(1000, 1))   # datos muy asimétricos

qt_uniforme = QuantileTransformer(output_distribution='uniform', random_state=0)
qt_normal = QuantileTransformer(output_distribution='normal', random_state=0)

X_unif = qt_uniforme.fit_transform(X)
X_norm = qt_normal.fit_transform(X)
```

### Características

- Es una transformación **no lineal**: cambia la forma de la distribución.
- Es **muy robusta a outliers**, porque solo importa el orden de los valores.
- Puede distorsionar relaciones lineales entre variables y es poco interpretable.
- Requiere una cantidad razonable de datos para estimar bien los cuantiles.

### Cuándo usarlo

Cuando las variables tienen distribuciones muy asimétricas o multimodales y el modelo se beneficia de entradas con distribución uniforme o normal.

---

## 8. PowerTransformer

### Idea

Aplica una transformación de potencia paramétrica que busca hacer los datos **lo más parecidos posible a una distribución normal**, estimando el parámetro $\lambda$ óptimo por máxima verosimilitud. Por defecto también estandariza el resultado (media 0, desviación 1).

### Métodos disponibles

| Método | Admite valores | Fórmula (para $\lambda \neq 0$) |
|---|---|---|
| `'box-cox'` | Solo estrictamente positivos | $\dfrac{x^\lambda - 1}{\lambda}$ |
| `'yeo-johnson'` (por defecto) | Positivos, cero y negativos | Extensión de Box-Cox para todo el dominio real |

### Ejemplo

```python
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method='yeo-johnson')   # standardize=True por defecto
X_pt = pt.fit_transform(X)
print(pt.lambdas_)   # lambda estimado para cada columna
```

### Características

- Transformación **no lineal y monótona** (preserva el orden).
- Reduce la asimetría y estabiliza la varianza.
- Más suave y paramétrica que QuantileTransformer, por lo que suele generalizar mejor con pocos datos.

### Cuándo usarlo

Con variables asimétricas (ingresos, conteos, tiempos) cuando el modelo asume normalidad o se beneficia de ella, como en regresión lineal o modelos gaussianos.

---

## 9. Tabla comparativa

| Escalador | Opera sobre | Rango del resultado | Robusto a outliers | Lineal | Preserva ceros / sparse | Uso típico |
|---|---|---|---|---|---|---|
| `StandardScaler` | Columnas | No acotado (media 0, desv. 1) | No | Sí | No (salvo `with_mean=False`) | Opción general |
| `MinMaxScaler` | Columnas | $[0, 1]$ o el indicado | No | Sí | No | Rangos fijos, imágenes |
| `MaxAbsScaler` | Columnas | $[-1, 1]$ | No | Sí | Sí | Datos dispersos |
| `RobustScaler` | Columnas | No acotado | Sí | Sí | Solo con `with_centering=False` | Datos con outliers |
| `Normalizer` | Filas | Norma 1 por fila | No aplica | Sí (por fila) | Sí | Textos, similitud coseno |
| `QuantileTransformer` | Columnas | $[0, 1]$ o normal | Sí | No | No | Distribuciones muy irregulares |
| `PowerTransformer` | Columnas | Aprox. normal estándar | Parcialmente | No | No | Variables asimétricas |

---

## 10. Buenas prácticas

### 10.1 Ajustar solo con datos de entrenamiento

El error más común es ajustar el escalador con todo el dataset antes de dividirlo. Eso filtra información del conjunto de prueba al entrenamiento (**data leakage**) y produce métricas demasiado optimistas.

```python
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)   # fit solo con entrenamiento
X_test_scaled = scaler.transform(X_test)         # solo transform en prueba
```

### 10.2 Usar Pipeline

Un `Pipeline` encadena el preprocesamiento con el modelo y garantiza que, en validación cruzada, el escalador se ajuste solo con los datos de entrenamiento de cada fold.

```python
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('modelo', LogisticRegression())
])

scores = cross_val_score(pipe, X, y, cv=5)
print(scores.mean())
```

### 10.3 Escalar columnas distintas de forma distinta

Con `ColumnTransformer` se puede aplicar un escalador diferente a cada grupo de columnas, y dejar sin escalar las variables categóricas ya codificadas.

```python
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocesador = ColumnTransformer([
    ('normales', StandardScaler(), ['edad', 'altura']),
    ('con_outliers', RobustScaler(), ['ingreso']),
    ('categoricas', OneHotEncoder(), ['region'])
])

pipe = Pipeline([
    ('prep', preprocesador),
    ('modelo', LogisticRegression())
])
```

### 10.4 No escalar la variable objetivo sin necesidad

En clasificación nunca se escala `y`. En regresión normalmente tampoco es necesario; si se quiere transformar `y` (por ejemplo, con un logaritmo), conviene usar `TransformedTargetRegressor`, que invierte la transformación automáticamente al predecir.

---

## 11. Guía rápida de decisión

1. **¿El modelo es basado en árboles?** Probablemente no necesites escalar.
2. **¿Los datos son dispersos (texto, conteos)?** Usa `MaxAbsScaler`, o `Normalizer` si importa la dirección del vector.
3. **¿Hay outliers importantes?** Usa `RobustScaler`, o `QuantileTransformer` si son extremos.
4. **¿Las variables son muy asimétricas?** Usa `PowerTransformer`.
5. **¿Necesitas un rango fijo?** Usa `MinMaxScaler`.
6. **En cualquier otro caso:** `StandardScaler` es un buen punto de partida.

Ante la duda, lo más sólido es comparar varios escaladores dentro de un `Pipeline` con validación cruzada (por ejemplo, con `GridSearchCV`) y elegir según el desempeño.

In [ ]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
# PARA IRIS vamos a usar un modelo de clasificación

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
# Cargar DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier # Importo el modelo

clf = DecisionTreeClassifier(random_state=0) # Instanciar el modelo

# Buscar los hiperparámetros

from sklearn.model_selection import train_test_split


X = df.drop("target", axis=1) # Generar las variables independientes

y = df["target"] # Generar la variable dependiente

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0) # Generar los sets de entrenamiento y testeo

clf.fit(X_train, y_train) # Ajuste del modelo

# Prediccion (Corregido 'pedict' por 'predict')
pred = clf.predict(X_test)

# Métricas

from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.9777777777777777

In [ ]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. Datos
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2. Modelo base sin ajustar (referencia)
base = DecisionTreeClassifier(random_state=42).fit(X_train, y_train)
print("Base  -> test:", accuracy_score(y_test, base.predict(X_test)))

# 3. Grilla de hiperparámetros
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [2, 3, 4, 5, 6, 8, None],
    'min_samples_leaf': [1, 2, 5, 10],
    'class_weight': [None, 'balanced']
}

# 4. Búsqueda con validación cruzada
grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='f1',
    return_train_score=True,
    n_jobs=-1
)
grid.fit(X_train, y_train)

# 5. Resultados de la búsqueda
print("Mejores hiperparámetros:", grid.best_params_)
print("F1 en validación cruzada:", round(grid.best_score_, 3))

tabla = pd.DataFrame(grid.cv_results_)
print(tabla[['params', 'mean_train_score', 'mean_test_score', 'std_test_score']]
      .sort_values('mean_test_score', ascending=False)
      .head(5))

# 6. Evaluación final en el conjunto de prueba
y_pred = grid.predict(X_test)
print("Ajustado -> test:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Profundidad final:", grid.best_estimator_.get_depth())
print("Número de hojas:", grid.best_estimator_.get_n_leaves())

Base  -> test: 0.9122807017543859
Mejores hiperparámetros: {'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 2}
F1 en validación cruzada: 0.958
                                               params  mean_train_score  \
65  {'class_weight': 'balanced', 'criterion': 'gin...          0.988529
68  {'class_weight': 'balanced', 'criterion': 'gin...          0.997366
69  {'class_weight': 'balanced', 'criterion': 'gin...          0.991184
73  {'class_weight': 'balanced', 'criterion': 'gin...          0.992932
81  {'class_weight': 'balanced', 'criterion': 'gin...          0.992932

    mean_test_score  std_test_score
65         0.957729        0.017569
68         0.954563        0.021404
69         0.954346        0.022956
73         0.952727        0.027127
81         0.952727        0.027127
Ajustado -> test: 0.9298245614035088
              precision    recall  f1-score   support

           0       0.89      0.93      0.91        42
           1       0.96      0.93      0.94        72

    accuracy                           0.93       114
   macro avg       0.92      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114

Profundidad final: 4
Número de hojas: 13

# Hiperparámetros y búsqueda con GridSearchCV: el caso de DecisionTree en scikit-learn

## 1. Parámetros vs. hiperparámetros

En aprendizaje automático conviene distinguir dos conceptos:

- **Parámetros**: valores que el modelo **aprende** a partir de los datos durante el entrenamiento. En un árbol de decisión son las variables elegidas en cada nodo y los umbrales de corte.
- **Hiperparámetros**: valores que se **definen antes** de entrenar y controlan cómo aprende el modelo. En un árbol de decisión son, por ejemplo, la profundidad máxima o el número mínimo de muestras por hoja.

Elegir bien los hiperparámetros es clave porque determinan el equilibrio entre **subajuste** (modelo demasiado simple) y **sobreajuste** (modelo que memoriza los datos de entrenamiento y generaliza mal).

Los árboles de decisión son especialmente propensos al sobreajuste: sin restricciones, crecen hasta que cada hoja es pura y alcanzan 100% de exactitud en entrenamiento, pero rinden peor en datos nuevos.

---

## 2. Principales hiperparámetros de DecisionTreeClassifier

```python
from sklearn.tree import DecisionTreeClassifier

modelo = DecisionTreeClassifier(
    criterion='gini',
    splitter='best',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    class_weight=None,
    ccp_alpha=0.0,
    random_state=42
)
```

Los valores mostrados son los que usa scikit-learn por defecto (salvo `random_state`).

### 2.1 criterion

Función que mide la calidad de una división (la impureza de los nodos).

| Valor | Descripción |
|---|---|
| `'gini'` (por defecto) | Índice de Gini: $G = 1 - \sum_k p_k^2$ |
| `'entropy'` | Entropía de Shannon: $H = -\sum_k p_k \log_2 p_k$ |
| `'log_loss'` | Equivalente a la entropía |

En la práctica Gini y entropía suelen dar resultados muy parecidos. Gini es levemente más rápido de calcular.

Para `DecisionTreeRegressor` los criterios son distintos: `'squared_error'`, `'friedman_mse'`, `'absolute_error'` y `'poisson'`.

### 2.2 max_depth

Profundidad máxima del árbol. Es el hiperparámetro **más importante** para controlar el sobreajuste.

- `None`: el árbol crece hasta que las hojas son puras o se alcanza otro límite.
- Valores bajos (2 a 5): árboles simples e interpretables, riesgo de subajuste.
- Valores altos: árboles complejos, riesgo de sobreajuste.

### 2.3 min_samples_split

Número mínimo de muestras que debe tener un nodo para poder dividirse. Acepta un entero (cantidad absoluta) o un decimal entre 0 y 1 (fracción del total de muestras). Valores más altos producen árboles más simples.

### 2.4 min_samples_leaf

Número mínimo de muestras que debe quedar en cada hoja. Evita hojas con muy pocos ejemplos, que suelen ser ruido. Suele ser más efectivo que `min_samples_split` para suavizar el modelo.

### 2.5 max_features

Número de variables consideradas al buscar la mejor división en cada nodo.

| Valor | Variables consideradas |
|---|---|
| `None` (por defecto) | Todas |
| `'sqrt'` | $\sqrt{n_{\text{features}}}$ |
| `'log2'` | $\log_2(n_{\text{features}})$ |
| entero | Esa cantidad |
| decimal | Esa fracción del total |

Reducirlo introduce aleatoriedad y diversidad. Es fundamental en Random Forest, pero en un árbol individual se usa menos.

### 2.6 max_leaf_nodes

Número máximo de hojas. El árbol crece priorizando las divisiones que más reducen la impureza hasta llegar a ese límite. Es una alternativa a `max_depth` para controlar la complejidad.

### 2.7 min_impurity_decrease

Un nodo solo se divide si la división reduce la impureza al menos en este valor. Permite descartar divisiones que aportan muy poco.

### 2.8 class_weight

Peso de cada clase. Con `'balanced'` los pesos se ajustan de forma inversamente proporcional a la frecuencia de cada clase. Es útil con **clases desbalanceadas**.

### 2.9 ccp_alpha

Parámetro de **poda por costo-complejidad** (cost complexity pruning). Primero se construye el árbol completo y luego se podan las ramas cuyo aporte no compensa su complejidad. Valores mayores producen árboles más pequeños. Se profundiza en la sección 7.

### 2.10 splitter

Estrategia para elegir la división: `'best'` (la mejor posible) o `'random'` (la mejor entre divisiones aleatorias). Casi siempre se deja en `'best'`.

### 2.11 random_state

Semilla para la aleatoriedad interna. Conviene fijarla para que los resultados sean **reproducibles**.

---

## 3. Configuración manual de hiperparámetros

La forma más simple es probar valores a mano y comparar resultados en un conjunto de validación. Se usará como ejemplo el dataset de cáncer de mama incluido en scikit-learn.

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

for profundidad in [1, 2, 3, 5, 10, None]:
    arbol = DecisionTreeClassifier(max_depth=profundidad, random_state=42)
    arbol.fit(X_train, y_train)
    acc_train = accuracy_score(y_train, arbol.predict(X_train))
    acc_test = accuracy_score(y_test, arbol.predict(X_test))
    print(f"max_depth={profundidad}: train={acc_train:.3f}  test={acc_test:.3f}")
```

Al ejecutar este código se observa el patrón típico: con `max_depth=None` la exactitud en entrenamiento llega a 1.000, pero la de prueba no mejora (o empeora) respecto a profundidades intermedias. Esa brecha es la señal del sobreajuste.

### Problema de este enfoque

Elegir hiperparámetros mirando el conjunto de **prueba** es un error metodológico: el conjunto de prueba deja de ser una estimación honesta del desempeño, porque se usó para tomar decisiones. Además, probar combinaciones a mano es lento cuando hay varios hiperparámetros. La solución es la **validación cruzada** combinada con una búsqueda sistemática.

---

## 4. Validación cruzada

En la validación cruzada de $k$ particiones (k-fold), el conjunto de entrenamiento se divide en $k$ partes. Se entrena $k$ veces, cada vez usando $k-1$ partes para entrenar y la parte restante para validar. El desempeño final es el promedio de las $k$ evaluaciones.

```python
from sklearn.model_selection import cross_val_score

arbol = DecisionTreeClassifier(max_depth=3, random_state=42)
scores = cross_val_score(arbol, X_train, y_train, cv=5, scoring='accuracy')

print(scores)          # exactitud en cada una de las 5 particiones
print(scores.mean())   # promedio
print(scores.std())    # variabilidad entre particiones
```

Así el conjunto de prueba queda reservado únicamente para la evaluación final.

El esquema completo de trabajo es:

```
Datos completos
 |
 +-- Entrenamiento (80%) --> búsqueda de hiperparámetros con validación cruzada
 |
 +-- Prueba (20%) -------> evaluación final, una sola vez
```

---

## 5. GridSearchCV: búsqueda exhaustiva en grilla

`GridSearchCV` prueba **todas las combinaciones** de una grilla de hiperparámetros, evalúa cada una con validación cruzada y se queda con la mejor.

### 5.1 Ejemplo básico

```python
from sklearn.model_selection import GridSearchCV

param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [2, 3, 4, 5, 6, 8, 10, None],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10]
}

grid = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,          # usa todos los núcleos del procesador
    verbose=1
)

grid.fit(X_train, y_train)
```

Número de combinaciones: $2 \times 8 \times 4 \times 4 = 256$. Con `cv=5` se entrenan $256 \times 5 = 1280$ árboles (más uno final).

### 5.2 Revisar los resultados

```python
print(grid.best_params_)    # mejor combinación encontrada
print(grid.best_score_)     # exactitud promedio en validación cruzada
mejor_arbol = grid.best_estimator_   # modelo ya reentrenado con todo X_train
```

Por defecto `refit=True`, de modo que `best_estimator_` ya está entrenado con todo el conjunto de entrenamiento usando la mejor combinación. Se puede usar directamente:

```python
from sklearn.metrics import classification_report

y_pred = grid.predict(X_test)   # equivalente a grid.best_estimator_.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
```

### 5.3 Analizar todas las combinaciones

El atributo `cv_results_` contiene el detalle de cada combinación. Es cómodo verlo como DataFrame:

```python
import pandas as pd

resultados = pd.DataFrame(grid.cv_results_)
columnas = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score']
print(resultados[columnas].sort_values('rank_test_score').head(10))
```

Es recomendable revisar no solo la mejor combinación, sino también las siguientes. Si varias combinaciones tienen un desempeño casi idéntico, conviene preferir la **más simple** (menor profundidad, más muestras por hoja), porque suele generalizar mejor y es más interpretable.

### 5.4 Ver también el desempeño en entrenamiento

Con `return_train_score=True` se puede comparar entrenamiento y validación para detectar sobreajuste:

```python
grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    return_train_score=True,
    n_jobs=-1
)
grid.fit(X_train, y_train)

resultados = pd.DataFrame(grid.cv_results_)
print(resultados[['params', 'mean_train_score', 'mean_test_score']].head())
```

Una gran diferencia entre `mean_train_score` y `mean_test_score` indica sobreajuste.

### 5.5 Grillas condicionales

`param_grid` también acepta una **lista de diccionarios**, útil cuando algunas combinaciones no tienen sentido o se quieren explorar zonas distintas:

```python
param_grid = [
    {'max_depth': [3, 5, 7], 'min_samples_leaf': [1, 5, 10]},
    {'max_depth': [None], 'ccp_alpha': [0.001, 0.005, 0.01, 0.02]}
]
```

Aquí se prueban 9 combinaciones del primer diccionario más 4 del segundo, en lugar de todas contra todas.

---

## 6. Métricas de evaluación (scoring)

El parámetro `scoring` define qué se optimiza. La elección depende del problema:

| Métrica | Valor en `scoring` | Cuándo usarla |
|---|---|---|
| Exactitud | `'accuracy'` | Clases balanceadas |
| Exactitud balanceada | `'balanced_accuracy'` | Clases desbalanceadas |
| F1 | `'f1'`, `'f1_macro'`, `'f1_weighted'` | Equilibrio entre precisión y recall |
| Recall | `'recall'` | Cuando los falsos negativos son costosos (diagnóstico médico) |
| Precisión | `'precision'` | Cuando los falsos positivos son costosos |
| AUC ROC | `'roc_auc'` | Capacidad de ranking del clasificador |

Se pueden calcular varias métricas a la vez, indicando con `refit` cuál decide el mejor modelo:

```python
grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid={'max_depth': [2, 3, 4, 5, 6, None]},
    cv=5,
    scoring={'acc': 'accuracy', 'f1': 'f1', 'recall': 'recall'},
    refit='f1',
    n_jobs=-1
)
grid.fit(X_train, y_train)
```

En regresión se usan métricas como `'neg_mean_squared_error'`, `'neg_mean_absolute_error'` o `'r2'`. Las métricas de error aparecen con signo negativo porque scikit-learn siempre **maximiza** el puntaje.

---

## 7. Poda por costo-complejidad con ccp_alpha

En lugar de limitar el crecimiento del árbol desde el inicio (pre-poda con `max_depth`, `min_samples_leaf`, etc.), la poda por costo-complejidad construye el árbol completo y luego elimina ramas (post-poda).

El criterio minimiza:

$$
R_\alpha(T) = R(T) + \alpha \, |T|
$$

donde $R(T)$ es el error (impureza total de las hojas), $|T|$ es el número de hojas y $\alpha$ penaliza la complejidad.

scikit-learn permite obtener los valores de $\alpha$ relevantes y usarlos en la grilla:

```python
arbol = DecisionTreeClassifier(random_state=42)
ruta = arbol.cost_complexity_pruning_path(X_train, y_train)
alphas = ruta.ccp_alphas[:-1]   # el último alpha deja solo la raíz

grid_alpha = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid={'ccp_alpha': alphas},
    cv=5,
    n_jobs=-1
)
grid_alpha.fit(X_train, y_train)

print(grid_alpha.best_params_)
print(grid_alpha.best_estimator_.get_n_leaves())   # número de hojas del árbol podado
```

Este enfoque tiene la ventaja de controlar la complejidad con **un solo hiperparámetro**.

---

## 8. RandomizedSearchCV: búsqueda aleatoria

Cuando la grilla es grande, `GridSearchCV` se vuelve muy costoso, porque el número de combinaciones crece multiplicativamente. `RandomizedSearchCV` prueba solo un número fijo de combinaciones (`n_iter`) muestreadas al azar, y permite usar **distribuciones** en lugar de listas.

```python
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

param_dist = {
    'criterion': ['gini', 'entropy'],
    'max_depth': randint(2, 20),
    'min_samples_split': randint(2, 50),
    'min_samples_leaf': randint(1, 30),
    'max_features': [None, 'sqrt', 'log2'],
    'ccp_alpha': uniform(0, 0.03)
}

random_search = RandomizedSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_distributions=param_dist,
    n_iter=100,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)
print(random_search.best_params_)
print(random_search.best_score_)
```

### Comparación

| Aspecto | GridSearchCV | RandomizedSearchCV |
|---|---|---|
| Combinaciones probadas | Todas | `n_iter` elegidas al azar |
| Costo | Crece multiplicativamente | Controlado por `n_iter` |
| Valores continuos | Solo los listados | Distribuciones completas |
| Garantía | Encuentra el mejor de la grilla | Puede no encontrar el óptimo exacto |
| Uso típico | Pocos hiperparámetros, grilla pequeña | Muchos hiperparámetros o espacio amplio |

Una estrategia habitual es combinarlas: primero una búsqueda aleatoria amplia para identificar la zona prometedora y luego una grilla fina alrededor de los mejores valores.

---

## 9. Curva de validación

`validation_curve` muestra cómo cambia el desempeño al variar **un solo** hiperparámetro. Es útil para visualizar el paso de subajuste a sobreajuste.

```python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import validation_curve

profundidades = np.arange(1, 16)

train_scores, val_scores = validation_curve(
    DecisionTreeClassifier(random_state=42),
    X_train, y_train,
    param_name='max_depth',
    param_range=profundidades,
    cv=5,
    scoring='accuracy'
)

plt.plot(profundidades, train_scores.mean(axis=1), marker='o', label='Entrenamiento')
plt.plot(profundidades, val_scores.mean(axis=1), marker='o', label='Validación')
plt.xlabel('max_depth')
plt.ylabel('Exactitud')
plt.legend()
plt.grid(True)
plt.show()
```

Interpretación típica del gráfico:

- **Profundidad baja**: ambas curvas bajas, el modelo subajusta.
- **Profundidad intermedia**: la curva de validación alcanza su máximo, zona óptima.
- **Profundidad alta**: entrenamiento cerca de 1.0 y validación estancada o en descenso, el modelo sobreajusta.

---

## 10. Búsqueda dentro de un Pipeline

Si hay preprocesamiento, debe ir dentro de un `Pipeline` para evitar data leakage en la validación cruzada. Los hiperparámetros se nombran con el formato `nombrepaso__hiperparametro` (doble guion bajo).

```python
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

pipe = Pipeline([
    ('imputador', SimpleImputer()),
    ('arbol', DecisionTreeClassifier(random_state=42))
])

param_grid = {
    'imputador__strategy': ['mean', 'median'],
    'arbol__max_depth': [3, 5, 7, None],
    'arbol__min_samples_leaf': [1, 5, 10]
}

grid = GridSearchCV(pipe, param_grid, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)
print(grid.best_params_)
```

Recordatorio: los árboles de decisión **no necesitan escalamiento**, por lo que en este caso no se incluye un `StandardScaler`.

---

## 11. Visualizar el árbol resultante

Una ventaja de los árboles es su interpretabilidad. Una vez encontrado el mejor modelo, se puede inspeccionar:

```python
from sklearn.tree import plot_tree, export_text
from sklearn.datasets import load_breast_cancer

datos = load_breast_cancer()
mejor = grid_alpha.best_estimator_

plt.figure(figsize=(20, 10))
plot_tree(
    mejor,
    feature_names=datos.feature_names,
    class_names=datos.target_names,
    filled=True,
    rounded=True
)
plt.show()

print(export_text(mejor, feature_names=list(datos.feature_names)))
```

También se puede revisar la importancia de cada variable:

```python
importancias = pd.Series(mejor.feature_importances_, index=datos.feature_names)
print(importancias.sort_values(ascending=False).head(10))
```

---

## 12. Buenas prácticas

1. **Separar el conjunto de prueba antes de todo** y usarlo una sola vez, al final.
2. **Usar `stratify=y`** en `train_test_split` para mantener la proporción de clases.
3. **Fijar `random_state`** en el modelo, en la división de datos y en la búsqueda aleatoria.
4. **Empezar con rangos amplios** y luego refinar alrededor de los mejores valores.
5. **Revisar si el mejor valor está en el borde de la grilla**: si `max_depth=10` gana y era el máximo probado, conviene ampliar el rango.
6. **No sobreinterpretar diferencias pequeñas** en `mean_test_score`; revisar `std_test_score`. Si dos combinaciones difieren menos que la desviación estándar, la diferencia probablemente no es significativa.
7. **Preferir el modelo más simple** entre combinaciones de desempeño similar.
8. **Elegir la métrica según el problema**, no usar exactitud por defecto con clases desbalanceadas.
9. **Controlar el costo computacional**: número de entrenamientos = combinaciones $\times$ particiones. Usar `n_jobs=-1` y, si la grilla es grande, `RandomizedSearchCV`.

---

## 13. Ejemplo completo

```python
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. Datos
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2. Modelo base sin ajustar (referencia)
base = DecisionTreeClassifier(random_state=42).fit(X_train, y_train)
print("Base  -> test:", accuracy_score(y_test, base.predict(X_test)))

# 3. Grilla de hiperparámetros
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [2, 3, 4, 5, 6, 8, None],
    'min_samples_leaf': [1, 2, 5, 10],
    'class_weight': [None, 'balanced']
}

# 4. Búsqueda con validación cruzada
grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='f1',
    return_train_score=True,
    n_jobs=-1
)
grid.fit(X_train, y_train)

# 5. Resultados de la búsqueda
print("Mejores hiperparámetros:", grid.best_params_)
print("F1 en validación cruzada:", round(grid.best_score_, 3))

tabla = pd.DataFrame(grid.cv_results_)
print(tabla[['params', 'mean_train_score', 'mean_test_score', 'std_test_score']]
      .sort_values('mean_test_score', ascending=False)
      .head(5))

# 6. Evaluación final en el conjunto de prueba
y_pred = grid.predict(X_test)
print("Ajustado -> test:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Profundidad final:", grid.best_estimator_.get_depth())
print("Número de hojas:", grid.best_estimator_.get_n_leaves())
```

Al comparar el modelo base con el ajustado, lo habitual es que el árbol ajustado sea **mucho más pequeño** (menos profundidad y hojas) con un desempeño en prueba igual o superior, lo que muestra que el control de la complejidad mejora la generalización.

![](https://media.licdn.com/dms/image/v2/D4D12AQH0NVHuB7sAJQ/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1726318143139?e=2147483647&v=beta&t=S-qSTdS2BFFRMQB5MuVyCCpP68i8zFt-3vAEVs5tDEo)

# Validación cruzada en scikit-learn

## 1. El problema: estimar cómo generaliza un modelo

El objetivo de un modelo de aprendizaje automático no es rendir bien con los datos que ya conoce, sino con **datos nuevos**. Evaluar un modelo con los mismos datos con los que se entrenó da una estimación demasiado optimista: un árbol de decisión sin restricciones, por ejemplo, alcanza 100% de exactitud en entrenamiento porque memoriza los ejemplos.

Por eso se necesita evaluar con datos que el modelo **no vio** durante el entrenamiento. La pregunta es cómo hacerlo de forma confiable.

---

## 2. Primer enfoque: división simple (hold-out)

La forma más directa es separar una parte de los datos para prueba:

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

modelo = DecisionTreeClassifier(max_depth=3, random_state=42)
modelo.fit(X_train, y_train)
print(accuracy_score(y_test, modelo.predict(X_test)))
```

### Limitaciones

1. **Alta varianza**: el resultado depende de qué ejemplos cayeron en prueba. Basta cambiar `random_state` para obtener una exactitud distinta.

    ```python
    for semilla in range(5):
        X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=semilla)
        m = DecisionTreeClassifier(max_depth=3, random_state=42).fit(X_tr, y_tr)
        print(f"semilla {semilla}: {accuracy_score(y_te, m.predict(X_te)):.3f}")
    ```

2. **Desperdicio de datos**: el 20% de prueba nunca se usa para entrenar. Con datasets pequeños esto es un costo importante.

3. **Riesgo de sobreajustar al conjunto de prueba**: si se usa repetidamente para elegir modelos o hiperparámetros, deja de ser una estimación honesta.

La validación cruzada resuelve los dos primeros problemas, y combinada con un conjunto de prueba reservado, también el tercero.

---

## 3. Validación cruzada k-fold

### Idea

1. Se dividen los datos en $k$ partes (folds) de tamaño similar.
2. Se entrena el modelo $k$ veces. En cada iteración, una parte se usa como validación y las $k-1$ restantes como entrenamiento.
3. Se obtienen $k$ puntajes y se reportan su **media** y su **desviación estándar**.

Esquema con $k = 5$ (V = validación, E = entrenamiento):

```
Iteración 1:  [ V ][ E ][ E ][ E ][ E ]
Iteración 2:  [ E ][ V ][ E ][ E ][ E ]
Iteración 3:  [ E ][ E ][ V ][ E ][ E ]
Iteración 4:  [ E ][ E ][ E ][ V ][ E ]
Iteración 5:  [ E ][ E ][ E ][ E ][ V ]
```

Cada ejemplo se usa **exactamente una vez** para validar y $k-1$ veces para entrenar.

### Estimación final

$$
\text{CV}_{k} = \frac{1}{k} \sum_{i=1}^{k} \text{puntaje}_i
$$

La desviación estándar entre folds indica qué tan **estable** es el modelo frente a cambios en los datos.

---

## 4. Funciones principales de scikit-learn

### 4.1 cross_val_score

La forma más simple. Devuelve un arreglo con el puntaje de cada fold.

```python
from sklearn.model_selection import cross_val_score

modelo = DecisionTreeClassifier(max_depth=3, random_state=42)

scores = cross_val_score(modelo, X, y, cv=5, scoring='accuracy')

print(scores)                                  # 5 puntajes
print(f"{scores.mean():.3f} +/- {scores.std():.3f}")
```

Detalle importante: cuando `cv` es un entero y el estimador es un **clasificador**, scikit-learn usa automáticamente `StratifiedKFold` (sin mezclar los datos). Para regresión usa `KFold`.

### 4.2 cross_validate

Más completa. Permite varias métricas a la vez, devuelve tiempos de entrenamiento y puntajes de entrenamiento, y opcionalmente los modelos entrenados.

```python
from sklearn.model_selection import cross_validate
import pandas as pd

resultados = cross_validate(
    modelo, X, y,
    cv=5,
    scoring=['accuracy', 'f1', 'recall', 'roc_auc'],
    return_train_score=True,
    return_estimator=False
)

df = pd.DataFrame(resultados)
print(df.round(3))
print(df.mean().round(3))
```

Claves del diccionario devuelto:

| Clave | Contenido |
|---|---|
| `fit_time` | Tiempo de entrenamiento en cada fold |
| `score_time` | Tiempo de evaluación en cada fold |
| `test_<métrica>` | Puntaje de validación por fold |
| `train_<métrica>` | Puntaje de entrenamiento por fold (si `return_train_score=True`) |
| `estimator` | Modelos entrenados (si `return_estimator=True`) |

Comparar `train_accuracy` con `test_accuracy` permite detectar **sobreajuste**: una brecha grande indica que el modelo memoriza.

### 4.3 cross_val_predict

Devuelve, para cada ejemplo, la predicción hecha por el modelo del fold en que ese ejemplo estuvo en validación. Es útil para construir matrices de confusión o gráficos con predicciones "fuera de muestra".

```python
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

y_pred = cross_val_predict(modelo, X, y, cv=5)

print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

# Probabilidades en lugar de clases
y_proba = cross_val_predict(modelo, X, y, cv=5, method='predict_proba')
```

Advertencia: `cross_val_predict` **no** es una forma de estimar el desempeño de generalización. Calcular una métrica sobre todas sus predicciones juntas no es equivalente al promedio de `cross_val_score`. Debe usarse para visualización y diagnóstico.

---

## 5. Estrategias de partición (iteradores de CV)

El parámetro `cv` acepta un entero o un **objeto divisor** que define cómo se generan los folds. Todos están en `sklearn.model_selection` y tienen el método `split(X, y, groups)`.

### 5.1 KFold

Divide en $k$ partes consecutivas. Por defecto **no mezcla** los datos.

```python
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for i, (idx_train, idx_val) in enumerate(kf.split(X)):
    print(f"Fold {i}: train={len(idx_train)}  val={len(idx_val)}")

scores = cross_val_score(modelo, X, y, cv=kf)
```

Si los datos vienen ordenados (por ejemplo, primero todos los de la clase 0 y luego los de la clase 1), usar `shuffle=False` puede producir folds sin ejemplos de alguna clase. Conviene usar `shuffle=True` salvo que el orden tenga significado (series temporales).

### 5.2 StratifiedKFold

Igual que KFold, pero cada fold mantiene la **misma proporción de clases** que el dataset completo. Es la opción recomendada para clasificación, especialmente con clases desbalanceadas.

```python
from sklearn.model_selection import StratifiedKFold
import numpy as np

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for i, (idx_train, idx_val) in enumerate(skf.split(X, y)):
    proporcion = np.bincount(y[idx_val]) / len(idx_val)
    print(f"Fold {i}: proporción de clases en validación = {proporcion.round(3)}")
```

### 5.3 RepeatedKFold y RepeatedStratifiedKFold

Repiten la validación cruzada varias veces con distintas mezclas. Reducen la varianza de la estimación, a cambio de más tiempo de cómputo.

```python
from sklearn.model_selection import RepeatedStratifiedKFold

rskf = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=42)
scores = cross_val_score(modelo, X, y, cv=rskf)

print(len(scores))   # 50 puntajes (5 folds x 10 repeticiones)
print(f"{scores.mean():.3f} +/- {scores.std():.3f}")
```

### 5.4 LeaveOneOut (LOO)

Caso extremo de k-fold con $k = n$: cada fold de validación tiene **un solo ejemplo**.

```python
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()
scores = cross_val_score(modelo, X, y, cv=loo)
print(scores.mean())   # cada puntaje individual es 0 o 1
```

- Ventaja: usa casi todos los datos para entrenar en cada iteración.
- Desventajas: requiere entrenar $n$ modelos (muy costoso) y la estimación tiene **alta varianza**.
- Se justifica solo con datasets muy pequeños.

`LeavePOut(p)` generaliza la idea dejando $p$ ejemplos fuera, pero el número de combinaciones crece muy rápido y casi nunca es práctico.

### 5.5 ShuffleSplit y StratifiedShuffleSplit

Generan un número arbitrario de divisiones aleatorias independientes de entrenamiento y validación. A diferencia de k-fold, un ejemplo puede aparecer en validación varias veces o ninguna.

```python
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=20, test_size=0.2, random_state=42)
scores = cross_val_score(modelo, X, y, cv=sss)
```

Útiles cuando se quiere controlar libremente el número de iteraciones y el tamaño de validación, o con datasets grandes donde k-fold completo es costoso.

### 5.6 Validación por grupos: GroupKFold, StratifiedGroupKFold, LeaveOneGroupOut

Cuando los datos tienen **grupos** (varias filas del mismo paciente, del mismo estudiante, de la misma escuela o de la misma sesión), las filas de un mismo grupo no son independientes. Si un grupo aparece tanto en entrenamiento como en validación, el modelo puede "reconocer" al individuo en lugar de aprender el patrón general, y la estimación queda inflada.

Los divisores por grupos garantizan que **todas las filas de un grupo queden del mismo lado**.

```python
from sklearn.model_selection import GroupKFold, LeaveOneGroupOut

# Ejemplo: cada fila pertenece a un estudiante
grupos = np.random.RandomState(0).randint(0, 30, size=len(y))   # 30 estudiantes ficticios

gkf = GroupKFold(n_splits=5)
scores = cross_val_score(modelo, X, y, cv=gkf, groups=grupos)

logo = LeaveOneGroupOut()   # un fold por grupo
scores_logo = cross_val_score(modelo, X, y, cv=logo, groups=grupos)
```

`StratifiedGroupKFold` combina ambas ideas: respeta los grupos e intenta mantener la proporción de clases.

### 5.7 TimeSeriesSplit

En series temporales no se puede mezclar: entrenar con datos del futuro para predecir el pasado es una forma de data leakage. `TimeSeriesSplit` usa siempre datos **anteriores** para entrenar y **posteriores** para validar, con una ventana de entrenamiento que crece.

```
Iteración 1:  [ E ][ V ]
Iteración 2:  [ E ][ E ][ V ]
Iteración 3:  [ E ][ E ][ E ][ V ]
Iteración 4:  [ E ][ E ][ E ][ E ][ V ]
Iteración 5:  [ E ][ E ][ E ][ E ][ E ][ V ]
```

```python
from sklearn.model_selection import TimeSeriesSplit

tscv = TimeSeriesSplit(n_splits=5)

for i, (idx_train, idx_val) in enumerate(tscv.split(X)):
    print(f"Fold {i}: train {idx_train[0]}-{idx_train[-1]}  val {idx_val[0]}-{idx_val[-1]}")
```

Parámetros útiles: `max_train_size` (ventana deslizante en lugar de creciente), `test_size` (tamaño fijo de validación) y `gap` (ejemplos que se descartan entre entrenamiento y validación para evitar dependencia temporal inmediata).

### 5.8 Resumen de estrategias

| Divisor | Mezcla | Respeta clases | Respeta grupos | Respeta orden temporal | Uso típico |
|---|---|---|---|---|---|
| `KFold` | Opcional | No | No | No | Regresión, datos i.i.d. |
| `StratifiedKFold` | Opcional | Sí | No | No | Clasificación (opción por defecto) |
| `RepeatedStratifiedKFold` | Sí | Sí | No | No | Estimaciones más estables |
| `LeaveOneOut` | No aplica | No | No | No | Datasets muy pequeños |
| `StratifiedShuffleSplit` | Sí | Sí | No | No | Muchas iteraciones, datos grandes |
| `GroupKFold` | No | No | Sí | No | Datos agrupados (pacientes, estudiantes) |
| `StratifiedGroupKFold` | Opcional | Sí | Sí | No | Grupos + clases desbalanceadas |
| `TimeSeriesSplit` | No | No | No | Sí | Series temporales |

---

## 6. Cómo elegir k

El valor de $k$ implica un compromiso:

| $k$ | Datos de entrenamiento por fold | Sesgo de la estimación | Varianza | Costo |
|---|---|---|---|---|
| Pequeño (2 a 3) | Pocos | Alto (pesimista) | Baja | Bajo |
| 5 a 10 | Mayoría | Moderado | Moderada | Moderado |
| $n$ (LOO) | Casi todos | Bajo | Alta | Muy alto |

- Con $k$ pequeño, cada modelo se entrena con menos datos que el modelo final, por lo que la estimación tiende a ser **pesimista**.
- Con $k$ grande, los conjuntos de entrenamiento se solapan mucho, los modelos se parecen entre sí y la estimación puede tener **más varianza**.

En la práctica, **$k = 5$ o $k = 10$** son los valores estándar y funcionan bien en la mayoría de los casos. Con datasets pequeños conviene usar $k = 10$ con repeticiones.

---

## 7. Data leakage y Pipeline

Un error frecuente es preprocesar todo el dataset **antes** de la validación cruzada:

```python
# INCORRECTO: el escalador ve los datos de validación de cada fold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X_escalado = StandardScaler().fit_transform(X)
scores = cross_val_score(LogisticRegression(max_iter=1000), X_escalado, y, cv=5)
```

En este caso la media y la desviación estándar se calculan con todos los datos, incluyendo los que luego servirán de validación. La información "se filtra" y la estimación queda optimista. El efecto es aún más grave con selección de variables, imputación basada en estadísticos o sobremuestreo (SMOTE).

La solución es poner el preprocesamiento dentro de un `Pipeline`, de modo que en cada fold se ajuste **solo con los datos de entrenamiento de ese fold**:

```python
# CORRECTO
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('escalador', StandardScaler()),
    ('modelo', LogisticRegression(max_iter=1000))
])

scores = cross_val_score(pipe, X, y, cv=5)
print(f"{scores.mean():.3f} +/- {scores.std():.3f}")
```

Regla general: **todo paso que aprenda algo de los datos debe ir dentro del Pipeline**.

---

## 8. Validación cruzada para selección de hiperparámetros

`GridSearchCV` y `RandomizedSearchCV` usan validación cruzada internamente para comparar combinaciones de hiperparámetros:

```python
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': [2, 3, 4, 5, 6, None], 'min_samples_leaf': [1, 5, 10]}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
)
grid.fit(X_train, y_train)

print(grid.best_params_)
print(grid.best_score_)
```

### Problema: best_score_ es optimista

`best_score_` es el máximo entre muchas combinaciones evaluadas sobre los mismos folds. Al elegir el máximo, parte de esa ventaja puede deberse al azar. Por eso **`best_score_` no es una estimación honesta** del desempeño del modelo final.

Hay dos soluciones:

1. **Conjunto de prueba reservado**: evaluar `grid` una sola vez en `X_test`, como se hizo arriba.
2. **Validación cruzada anidada**, explicada a continuación.

---

## 9. Validación cruzada anidada (nested CV)

Usa dos niveles de validación cruzada:

- **Ciclo interno**: selecciona los hiperparámetros (GridSearchCV).
- **Ciclo externo**: evalúa el procedimiento completo, incluida la selección de hiperparámetros, en datos que el ciclo interno nunca vio.

```
Ciclo externo (evaluación)
 |
 +-- Fold externo 1: entrenamiento externo --> Ciclo interno (GridSearchCV con k folds)
 |                   validación externa   --> evalúa el mejor modelo encontrado
 +-- Fold externo 2: ...
 +-- ...
```

```python
cv_interno = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)
cv_externo = StratifiedKFold(n_splits=5, shuffle=True, random_state=2)

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=cv_interno
)

scores_anidados = cross_val_score(grid, X, y, cv=cv_externo)

print(f"CV anidada: {scores_anidados.mean():.3f} +/- {scores_anidados.std():.3f}")
```

Al comparar con `grid.best_score_` (no anidado), lo habitual es que la estimación anidada sea algo **menor**: esa diferencia es el optimismo que introduce la selección de hiperparámetros.

La CV anidada estima el desempeño **del procedimiento** de modelado, no de un modelo concreto. Para obtener el modelo final, se ejecuta `grid.fit(X, y)` sobre todos los datos.

---

## 10. Interpretar los resultados

### Media y desviación estándar

Reportar solo la media oculta información. Siempre conviene reportar **media y desviación estándar** (o un intervalo):

```python
print(f"Exactitud: {scores.mean():.3f} +/- {scores.std():.3f}")
```

- Una desviación estándar **alta** indica que el desempeño depende mucho de qué datos se usan para entrenar: modelo inestable o dataset pequeño.
- Si dos modelos tienen medias que difieren menos que sus desviaciones, la diferencia probablemente **no es significativa**.

### Comparar modelos con los mismos folds

Para que la comparación sea justa, todos los modelos deben evaluarse sobre **las mismas particiones**. Se logra pasando el mismo objeto divisor con `random_state` fijo:

```python
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

modelos = {
    'Árbol (depth=3)': DecisionTreeClassifier(max_depth=3, random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'KNN': Pipeline([('esc', StandardScaler()), ('knn', KNeighborsClassifier())]),
    'Reg. logística': Pipeline([('esc', StandardScaler()),
                                ('lr', LogisticRegression(max_iter=1000))])
}

for nombre, m in modelos.items():
    s = cross_val_score(m, X, y, cv=cv)
    print(f"{nombre:18s} {s.mean():.3f} +/- {s.std():.3f}")
```

---

## 11. Curva de aprendizaje

`learning_curve` usa validación cruzada para mostrar cómo cambia el desempeño al aumentar el tamaño del conjunto de entrenamiento. Ayuda a decidir si conviene conseguir más datos o cambiar de modelo.

```python
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve

tamanos, train_scores, val_scores = learning_curve(
    DecisionTreeClassifier(max_depth=3, random_state=42),
    X, y,
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
    train_sizes=np.linspace(0.1, 1.0, 10),
    scoring='accuracy'
)

plt.plot(tamanos, train_scores.mean(axis=1), marker='o', label='Entrenamiento')
plt.plot(tamanos, val_scores.mean(axis=1), marker='o', label='Validación')
plt.fill_between(tamanos,
                 val_scores.mean(axis=1) - val_scores.std(axis=1),
                 val_scores.mean(axis=1) + val_scores.std(axis=1),
                 alpha=0.2)
plt.xlabel('Tamaño del conjunto de entrenamiento')
plt.ylabel('Exactitud')
plt.legend()
plt.grid(True)
plt.show()
```

Interpretación:

- **Ambas curvas bajas y cercanas**: subajuste (sesgo alto). Más datos no ayudan; conviene un modelo más complejo.
- **Entrenamiento alto y validación baja, con brecha que se reduce al aumentar los datos**: sobreajuste (varianza alta). Más datos o más regularización pueden ayudar.
- **Ambas curvas altas y convergentes**: buen ajuste.

---

## 12. Buenas prácticas

1. **Reservar un conjunto de prueba** al inicio y usarlo una sola vez, al final de todo el proceso.
2. **Usar `StratifiedKFold`** en clasificación, sobre todo con clases desbalanceadas.
3. **Usar `shuffle=True` con `random_state` fijo**, salvo en series temporales.
4. **Poner todo el preprocesamiento dentro de un `Pipeline`** para evitar data leakage.
5. **Respetar la estructura de los datos**: `GroupKFold` si hay observaciones dependientes, `TimeSeriesSplit` si hay orden temporal.
6. **Reportar media y desviación estándar**, no solo la media.
7. **Comparar modelos con los mismos folds**.
8. **No tomar `best_score_` de GridSearchCV como desempeño final**; usar el conjunto de prueba o CV anidada.
9. **Usar $k = 5$ o $k = 10$** como punto de partida, con repeticiones si el dataset es pequeño.
10. **Elegir la métrica según el problema** (F1, recall o AUC con clases desbalanceadas, no solo exactitud).

---

## 13. Ejemplo completo

```python
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                     cross_validate, GridSearchCV, cross_val_score)
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# 1. Datos y conjunto de prueba reservado
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 2. Evaluación de un modelo base con validación cruzada
base = DecisionTreeClassifier(random_state=42)
res = cross_validate(base, X_train, y_train, cv=cv,
                     scoring=['accuracy', 'f1'], return_train_score=True)
print(pd.DataFrame(res).mean().round(3))
# Se espera train_accuracy = 1.0 y test_accuracy menor: sobreajuste

# 3. Búsqueda de hiperparámetros con validación cruzada
param_grid = {'max_depth': [2, 3, 4, 5, 6, None],
              'min_samples_leaf': [1, 2, 5, 10]}

grid = GridSearchCV(DecisionTreeClassifier(random_state=42),
                    param_grid, cv=cv, scoring='f1', n_jobs=-1)
grid.fit(X_train, y_train)
print("Mejores hiperparámetros:", grid.best_params_)
print("F1 CV (optimista):", round(grid.best_score_, 3))

# 4. Estimación honesta del procedimiento con CV anidada
cv_externo = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)
anidada = cross_val_score(grid, X_train, y_train, cv=cv_externo, scoring='f1')
print(f"F1 CV anidada: {anidada.mean():.3f} +/- {anidada.std():.3f}")

# 5. Evaluación final, una sola vez, en el conjunto de prueba
y_pred = grid.predict(X_test)
print(classification_report(y_test, y_pred))
```

El flujo resume la lógica completa: la validación cruzada se usa para **diagnosticar** el modelo, **seleccionar** hiperparámetros y **estimar** el desempeño del procedimiento, mientras que el conjunto de prueba queda reservado para la **verificación final**.

# Regularización y validación: Ridge, Lasso y ElasticNet en scikit-learn

## 1. Punto de partida: regresión lineal y sobreajuste

La regresión lineal ordinaria (mínimos cuadrados, `LinearRegression`) busca los coeficientes $w$ que minimizan el error cuadrático:

$$
\min_w \; \lVert y - Xw \rVert_2^2
$$

Funciona bien cuando hay muchos más ejemplos que variables y las variables no están muy correlacionadas. Pero tiene problemas cuando:

- Hay **muchas variables** en relación con el número de ejemplos.
- Hay **multicolinealidad** (variables muy correlacionadas entre sí): los coeficientes se vuelven inestables y pueden tomar valores enormes con signos opuestos que se compensan.
- Se agregan **variables polinómicas** o interacciones: el modelo gana flexibilidad y sobreajusta.

En estos casos los coeficientes crecen mucho para ajustar el ruido del entrenamiento y el modelo generaliza mal.

### Idea de la regularización

La regularización agrega una **penalización** al tamaño de los coeficientes:

$$
\min_w \; \text{Error}(w) + \alpha \cdot \text{Penalización}(w)
$$

- $\alpha = 0$: equivale a regresión lineal ordinaria.
- $\alpha$ grande: los coeficientes se encogen hacia cero, el modelo se vuelve más simple.

El hiperparámetro $\alpha$ controla el **equilibrio entre sesgo y varianza**, y por eso debe elegirse con **validación**. Ese es el foco de esta guía.

---

## 2. Ridge (penalización L2)

### Función objetivo en scikit-learn

$$
\min_w \; \lVert y - Xw \rVert_2^2 + \alpha \lVert w \rVert_2^2
\qquad\text{con}\qquad
\lVert w \rVert_2^2 = \sum_j w_j^2
$$

### Características

- Encoge todos los coeficientes hacia cero, pero **nunca los hace exactamente cero**.
- Maneja muy bien la **multicolinealidad**: reparte el peso entre variables correlacionadas en lugar de elegir una.
- Tiene solución cerrada, por lo que es rápido.
- No hace selección de variables: el modelo final usa todas.

### Ejemplo

```python
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score

X, y = load_diabetes(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

ridge = Ridge(alpha=1.0)   # alpha=1.0 por defecto
ridge.fit(X_train, y_train)

print(ridge.coef_)
print("R2 test:", r2_score(y_test, ridge.predict(X_test)))
```

---

## 3. Lasso (penalización L1)

### Función objetivo en scikit-learn

$$
\min_w \; \frac{1}{2n} \lVert y - Xw \rVert_2^2 + \alpha \lVert w \rVert_1
\qquad\text{con}\qquad
\lVert w \rVert_1 = \sum_j |w_j|
$$

### Características

- Puede llevar coeficientes **exactamente a cero**: realiza **selección automática de variables**.
- Produce modelos **dispersos** (sparse) e interpretables.
- Con variables muy correlacionadas tiende a elegir **una arbitrariamente** y descartar las demás, lo que puede ser inestable.
- Si hay más variables que ejemplos ($p > n$), selecciona como máximo $n$ variables.
- No tiene solución cerrada; se resuelve con descenso por coordenadas (parámetros `max_iter` y `tol`).

### Ejemplo

```python
from sklearn.linear_model import Lasso
import numpy as np

lasso = Lasso(alpha=0.1, max_iter=10000)
lasso.fit(X_train, y_train)

print(lasso.coef_)
print("Variables seleccionadas:", np.sum(lasso.coef_ != 0), "de", X.shape[1])
print("R2 test:", r2_score(y_test, lasso.predict(X_test)))
```

### Advertencia sobre la escala de alpha

Las funciones objetivo de Ridge y Lasso en scikit-learn **no están en la misma escala**: Lasso divide el error por $2n$ y Ridge no. Por eso un mismo valor de $\alpha$ tiene efectos muy distintos en ambos modelos. **No se debe reutilizar el alpha óptimo de uno en el otro**; cada uno se valida por separado.

---

## 4. ElasticNet (combinación L1 + L2)

### Función objetivo en scikit-learn

$$
\min_w \; \frac{1}{2n} \lVert y - Xw \rVert_2^2
+ \alpha \cdot \rho \, \lVert w \rVert_1
+ \frac{\alpha (1 - \rho)}{2} \lVert w \rVert_2^2
$$

donde $\rho$ corresponde al parámetro `l1_ratio`.

| `l1_ratio` | Comportamiento |
|---|---|
| 1.0 | Equivale a Lasso |
| 0.0 | Penalización solo L2 (similar a Ridge, pero en la escala de ElasticNet) |
| Entre 0 y 1 | Mezcla de ambas |

### Características

- Hace **selección de variables** como Lasso.
- Con variables correlacionadas tiende a **seleccionarlas en grupo**, como Ridge, en lugar de elegir una al azar.
- Más estable que Lasso cuando $p > n$ o hay fuerte correlación.
- Tiene **dos hiperparámetros** que validar: `alpha` y `l1_ratio`.

### Ejemplo

```python
from sklearn.linear_model import ElasticNet

enet = ElasticNet(alpha=0.1, l1_ratio=0.5, max_iter=10000)   # valores por defecto: alpha=1.0, l1_ratio=0.5
enet.fit(X_train, y_train)

print(enet.coef_)
print("R2 test:", r2_score(y_test, enet.predict(X_test)))
```

---

## 5. Comparación de los tres modelos

| Aspecto | Ridge | Lasso | ElasticNet |
|---|---|---|---|
| Penalización | L2 ($\sum w_j^2$) | L1 ($\sum \lvert w_j \rvert$) | L1 + L2 |
| Coeficientes en cero | No | Sí | Sí |
| Selección de variables | No | Sí | Sí |
| Variables correlacionadas | Reparte el peso | Elige una | Las selecciona en grupo |
| Hiperparámetros | `alpha` | `alpha` | `alpha`, `l1_ratio` |
| Solución cerrada | Sí | No | No |
| Versión con CV integrada | `RidgeCV` | `LassoCV` | `ElasticNetCV` |
| Cuándo usarlo | Muchas variables útiles, multicolinealidad | Se sospecha que pocas variables importan | Muchas variables correlacionadas y se quiere selección |

---

## 6. Requisito previo: escalar las variables

La penalización actúa sobre el **tamaño de los coeficientes**, y ese tamaño depende de la escala de cada variable. Si una variable está en metros y otra en milímetros, la segunda tendrá un coeficiente mil veces menor y será penalizada mucho menos. Sin escalamiento, la regularización castiga de forma arbitraria.

Por eso, con Ridge, Lasso y ElasticNet **siempre se deben estandarizar las variables**, y siempre **dentro de un Pipeline** para evitar data leakage durante la validación:

```python
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe_ridge = Pipeline([
    ('escalador', StandardScaler()),
    ('modelo', Ridge(alpha=1.0))
])
```

El dataset `load_diabetes` ya viene estandarizado, pero se mantiene el escalador en los ejemplos porque en datos reales casi nunca es así.

El intercepto (`fit_intercept=True` por defecto) **no se penaliza**.

---

## 7. Efecto de alpha: trayectoria de los coeficientes

Antes de validar, es útil ver cómo cambian los coeficientes al variar $\alpha$. Como alpha opera en escala multiplicativa, siempre se exploran valores en **escala logarítmica** con `np.logspace`.

```python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

X_train_esc = StandardScaler().fit_transform(X_train)   # solo para la visualización

alphas = np.logspace(-3, 3, 100)   # de 0.001 a 1000
coefs_ridge, coefs_lasso = [], []

for a in alphas:
    coefs_ridge.append(Ridge(alpha=a).fit(X_train_esc, y_train).coef_)
    coefs_lasso.append(Lasso(alpha=a, max_iter=10000).fit(X_train_esc, y_train).coef_)

fig, ejes = plt.subplots(1, 2, figsize=(14, 5))
for eje, coefs, titulo in zip(ejes, [coefs_ridge, coefs_lasso], ['Ridge', 'Lasso']):
    eje.plot(alphas, coefs)
    eje.set_xscale('log')
    eje.set_xlabel('alpha')
    eje.set_ylabel('Coeficiente')
    eje.set_title(f'Trayectoria de coeficientes: {titulo}')
    eje.axhline(0, color='black', linewidth=0.5)
plt.show()
```

Lo que se observa:

- **Ridge**: todos los coeficientes se acercan a cero de forma suave a medida que alpha crece, pero ninguno llega exactamente a cero.
- **Lasso**: los coeficientes van llegando a cero **uno por uno**. Las variables que sobreviven con alpha alto son las más relevantes.

scikit-learn también ofrece `lasso_path` y `enet_path` para calcular estas trayectorias de forma eficiente.

---

## 8. Validación con GridSearchCV

La forma más general y metodológicamente más limpia es usar `GridSearchCV` con un Pipeline. Así el escalador se ajusta solo con los datos de entrenamiento de cada fold.

### 8.1 Ridge

```python
from sklearn.model_selection import GridSearchCV, KFold

cv = KFold(n_splits=5, shuffle=True, random_state=42)

pipe_ridge = Pipeline([
    ('escalador', StandardScaler()),
    ('modelo', Ridge())
])

grid_ridge = GridSearchCV(
    pipe_ridge,
    param_grid={'modelo__alpha': np.logspace(-3, 3, 50)},
    cv=cv,
    scoring='neg_mean_squared_error',
    return_train_score=True,
    n_jobs=-1
)
grid_ridge.fit(X_train, y_train)

print("Mejor alpha:", grid_ridge.best_params_['modelo__alpha'])
print("MSE CV:", -grid_ridge.best_score_)
```

### 8.2 Lasso

```python
pipe_lasso = Pipeline([
    ('escalador', StandardScaler()),
    ('modelo', Lasso(max_iter=10000))
])

grid_lasso = GridSearchCV(
    pipe_lasso,
    param_grid={'modelo__alpha': np.logspace(-3, 1, 50)},
    cv=cv,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)
grid_lasso.fit(X_train, y_train)

print("Mejor alpha:", grid_lasso.best_params_['modelo__alpha'])
coefs = grid_lasso.best_estimator_.named_steps['modelo'].coef_
print("Variables seleccionadas:", np.sum(coefs != 0))
```

### 8.3 ElasticNet (dos hiperparámetros)

```python
pipe_enet = Pipeline([
    ('escalador', StandardScaler()),
    ('modelo', ElasticNet(max_iter=10000))
])

grid_enet = GridSearchCV(
    pipe_enet,
    param_grid={
        'modelo__alpha': np.logspace(-3, 1, 30),
        'modelo__l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0]
    },
    cv=cv,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)
grid_enet.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid_enet.best_params_)
```

Para `l1_ratio` conviene incluir más valores cerca de 1, porque en esa zona el comportamiento cambia más.

### 8.4 Métricas de regresión para scoring

| Métrica | Valor en `scoring` | Comentario |
|---|---|---|
| Error cuadrático medio | `'neg_mean_squared_error'` | Penaliza fuerte los errores grandes |
| Raíz del ECM | `'neg_root_mean_squared_error'` | Misma unidad que `y`, más interpretable |
| Error absoluto medio | `'neg_mean_absolute_error'` | Más robusto a outliers |
| Coeficiente de determinación | `'r2'` | Proporción de varianza explicada |

Las métricas de error tienen signo negativo porque scikit-learn siempre **maximiza** el puntaje. Para reportarlas se les cambia el signo.

---

## 9. Estimadores con validación cruzada integrada

scikit-learn ofrece versiones de estos modelos que **ya incluyen la validación cruzada** para elegir alpha. Son más eficientes que GridSearchCV porque aprovechan la estructura matemática del problema.

### 9.1 RidgeCV

```python
from sklearn.linear_model import RidgeCV

ridge_cv = RidgeCV(alphas=np.logspace(-3, 3, 100))   # cv=None por defecto
ridge_cv.fit(X_train_esc, y_train)

print("Mejor alpha:", ridge_cv.alpha_)
```

Detalle importante: con `cv=None` (por defecto), `RidgeCV` usa **validación cruzada leave-one-out eficiente** (Generalized Cross-Validation). Gracias a la solución cerrada de Ridge, calcula el error LOO de todos los alphas casi al costo de un solo ajuste. Si se pasa `cv=5` u otro divisor, usa k-fold normal, que es más lento.

### 9.2 LassoCV

```python
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(
    alphas=np.logspace(-3, 1, 100),
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    max_iter=10000,
    n_jobs=-1
)
lasso_cv.fit(X_train_esc, y_train)

print("Mejor alpha:", lasso_cv.alpha_)
print("Coeficientes:", lasso_cv.coef_)
```

Si no se entregan `alphas`, `LassoCV` construye automáticamente una grilla de 100 valores entre el alpha mínimo que anula todos los coeficientes y una fracción de él. Esa grilla automática suele ser una buena elección.

Atributos útiles:

| Atributo | Contenido |
|---|---|
| `alpha_` | Alpha elegido |
| `alphas_` | Grilla de alphas evaluada |
| `mse_path_` | ECM de cada alpha en cada fold, forma `(n_alphas, n_folds)` |
| `coef_` | Coeficientes del modelo final, reentrenado con todos los datos |

### 9.3 ElasticNetCV

```python
from sklearn.linear_model import ElasticNetCV

enet_cv = ElasticNetCV(
    l1_ratio=[0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0],
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    max_iter=10000,
    n_jobs=-1
)
enet_cv.fit(X_train_esc, y_train)

print("Mejor alpha:", enet_cv.alpha_)
print("Mejor l1_ratio:", enet_cv.l1_ratio_)
```

Aquí `mse_path_` tiene forma `(n_l1_ratio, n_alphas, n_folds)`.

### 9.4 Precaución con el escalamiento

En los ejemplos de esta sección se escaló `X_train` completo **antes** de la validación cruzada interna, lo que introduce una pequeña filtración de información entre folds. Hay dos opciones:

1. **Aceptarla** como aproximación práctica: con StandardScaler y datasets de tamaño razonable el efecto suele ser pequeño.
2. **Evitarla del todo** usando `GridSearchCV` con Pipeline (sección 8), donde el escalador se reajusta en cada fold.

Poner `LassoCV` dentro de un Pipeline (`Pipeline([('esc', StandardScaler()), ('m', LassoCV())])`) **no resuelve** el problema: el escalador se ajusta una vez con todo el conjunto y luego `LassoCV` hace su validación interna sobre datos ya escalados.

### 9.5 GridSearchCV vs. estimadores CV

| Aspecto | GridSearchCV + Pipeline | RidgeCV / LassoCV / ElasticNetCV |
|---|---|---|
| Velocidad | Más lento | Mucho más rápido |
| Escalamiento por fold | Correcto | Requiere escalar antes (leve leakage) |
| Métricas | Cualquier `scoring` | Principalmente ECM (RidgeCV acepta `scoring`) |
| Combinar con otros pasos | Sí (imputación, polinomios, etc.) | Limitado |
| Recomendado para | Rigor metodológico, pipelines complejos | Exploración rápida, datasets grandes |

---

## 10. Visualizar la curva de validación

### 10.1 Error de validación en función de alpha

```python
mse_medio = lasso_cv.mse_path_.mean(axis=1)
mse_std = lasso_cv.mse_path_.std(axis=1)

plt.figure(figsize=(8, 5))
plt.plot(lasso_cv.alphas_, mse_medio, label='ECM medio (CV)')
plt.fill_between(lasso_cv.alphas_, mse_medio - mse_std, mse_medio + mse_std, alpha=0.2)
plt.axvline(lasso_cv.alpha_, linestyle='--', color='black', label='alpha elegido')
plt.xscale('log')
plt.xlabel('alpha')
plt.ylabel('ECM')
plt.title('LassoCV: error de validación cruzada')
plt.legend()
plt.show()
```

Interpretación típica (de izquierda a derecha):

- **Alpha muy pequeño**: casi sin regularización, posible sobreajuste; el error de validación es algo mayor.
- **Alpha intermedio**: zona óptima, error mínimo.
- **Alpha muy grande**: todos los coeficientes cerca de cero, el modelo predice casi la media; el error crece rápidamente (subajuste).

### 10.2 Entrenamiento vs. validación

Con `validation_curve` se ven ambas curvas y la brecha entre ellas:

```python
from sklearn.model_selection import validation_curve

alphas = np.logspace(-3, 3, 30)
train_s, val_s = validation_curve(
    pipe_ridge, X_train, y_train,
    param_name='modelo__alpha', param_range=alphas,
    cv=cv, scoring='neg_mean_squared_error'
)

plt.plot(alphas, -train_s.mean(axis=1), marker='o', label='Entrenamiento')
plt.plot(alphas, -val_s.mean(axis=1), marker='o', label='Validación')
plt.xscale('log')
plt.xlabel('alpha')
plt.ylabel('ECM')
plt.legend()
plt.show()
```

A medida que alpha crece, el error de **entrenamiento siempre aumenta** (el modelo pierde flexibilidad), mientras que el de **validación primero baja y luego sube**.

### 10.3 Si el óptimo está en el borde

Si el alpha elegido es el menor o el mayor de la grilla, el verdadero óptimo puede estar fuera del rango explorado. En ese caso hay que **ampliar la grilla** en esa dirección y volver a validar.

---

## 11. Regla de una desviación estándar

El alpha con el menor error de validación no siempre es la mejor elección. Si varios alphas tienen un error estadísticamente indistinguible, conviene elegir el **más simple** (el mayor alpha), porque produce un modelo más regularizado y, en Lasso, con menos variables.

La **regla de una desviación estándar** (one-standard-error rule) elige el mayor alpha cuyo error medio esté dentro de una desviación estándar (o un error estándar) del mínimo:

```python
mse_medio = lasso_cv.mse_path_.mean(axis=1)
mse_se = lasso_cv.mse_path_.std(axis=1) / np.sqrt(lasso_cv.mse_path_.shape[1])

idx_min = np.argmin(mse_medio)
umbral = mse_medio[idx_min] + mse_se[idx_min]

alpha_1se = lasso_cv.alphas_[mse_medio <= umbral].max()

lasso_1se = Lasso(alpha=alpha_1se, max_iter=10000).fit(X_train_esc, y_train)

print("Alpha mínimo error:", lasso_cv.alpha_, "->", np.sum(lasso_cv.coef_ != 0), "variables")
print("Alpha regla 1-SE:  ", alpha_1se, "->", np.sum(lasso_1se.coef_ != 0), "variables")
```

Esta regla es especialmente útil en Lasso cuando el objetivo incluye **interpretabilidad** y selección de variables.

---

## 12. Alternativa sin validación cruzada: criterios de información

Para Lasso, `LassoLarsIC` elige alpha usando los criterios **AIC** o **BIC** en lugar de validación cruzada. Es mucho más rápido porque ajusta el modelo una sola vez.

```python
from sklearn.linear_model import LassoLarsIC

lasso_bic = LassoLarsIC(criterion='bic')
lasso_bic.fit(X_train_esc, y_train)

print("Alpha (BIC):", lasso_bic.alpha_)
print("Variables seleccionadas:", np.sum(lasso_bic.coef_ != 0))
```

- **BIC** penaliza más la complejidad y tiende a elegir modelos más pequeños.
- **AIC** tiende a elegir modelos algo más grandes.

Estos criterios suponen que el modelo está bien especificado y que hay más ejemplos que variables. Cuando esos supuestos no se cumplen, la validación cruzada es más confiable.

---

## 13. Evaluación final y comparación honesta

Como en cualquier búsqueda de hiperparámetros, el error de validación del mejor alpha es **optimista**. La evaluación final se hace una sola vez en el conjunto de prueba, o bien con validación cruzada anidada.

### 13.1 Comparar los modelos en el conjunto de prueba

```python
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

modelos = {
    'Lineal': Pipeline([('esc', StandardScaler()), ('m', LinearRegression())]).fit(X_train, y_train),
    'Ridge': grid_ridge.best_estimator_,
    'Lasso': grid_lasso.best_estimator_,
    'ElasticNet': grid_enet.best_estimator_,
}

for nombre, m in modelos.items():
    pred = m.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    print(f"{nombre:12s} RMSE={rmse:7.2f}  R2={r2_score(y_test, pred):.3f}")
```

### 13.2 Validación cruzada anidada

```python
from sklearn.model_selection import cross_val_score

cv_externo = KFold(n_splits=5, shuffle=True, random_state=7)

for nombre, grid in [('Ridge', grid_ridge), ('Lasso', grid_lasso), ('ElasticNet', grid_enet)]:
    scores = cross_val_score(grid, X_train, y_train, cv=cv_externo,
                             scoring='neg_root_mean_squared_error')
    print(f"{nombre:12s} RMSE anidado = {-scores.mean():.2f} +/- {scores.std():.2f}")
```

Si las diferencias entre modelos son menores que la desviación estándar, no hay evidencia de que uno sea mejor; en ese caso se puede preferir el más simple o el más interpretable.

---

## 14. Regularización en clasificación

Las mismas ideas aplican a `LogisticRegression`, con dos diferencias importantes:

- La intensidad de la regularización se controla con **`C = 1/alpha`**: un `C` **pequeño** implica **más** regularización.
- El tipo de penalización se elige con `penalty` (`'l2'` por defecto, `'l1'`, `'elasticnet'`), y algunos tipos requieren un `solver` específico (`'liblinear'` o `'saga'` para L1, `'saga'` para elasticnet).

```python
from sklearn.linear_model import LogisticRegressionCV

clf = LogisticRegressionCV(
    Cs=np.logspace(-3, 3, 20),
    penalty='l1',
    solver='saga',
    cv=5,
    max_iter=5000
)
```

---

## 15. Buenas prácticas

1. **Estandarizar siempre** las variables antes de regularizar, dentro de un Pipeline.
2. **Explorar alpha en escala logarítmica** (`np.logspace`), cubriendo varios órdenes de magnitud.
3. **Verificar que el óptimo no esté en el borde** de la grilla; si lo está, ampliarla.
4. **No comparar valores de alpha entre Ridge y Lasso**: sus funciones objetivo están en escalas distintas.
5. **Usar `shuffle=True`** en KFold si los datos pueden venir ordenados. Los estimadores CV usan KFold sin mezclar por defecto cuando se les pasa un entero.
6. **Aumentar `max_iter`** en Lasso y ElasticNet si aparece una `ConvergenceWarning`.
7. **Considerar la regla de una desviación estándar** cuando se busca un modelo más simple o interpretable.
8. **Usar `GridSearchCV` con Pipeline** cuando se requiere rigor (escalamiento por fold, otros pasos de preprocesamiento); usar `RidgeCV`, `LassoCV` o `ElasticNetCV` para exploración rápida.
9. **Evaluar en el conjunto de prueba una sola vez** o usar CV anidada para estimar el desempeño real.
10. **Interpretar con cuidado la selección de Lasso**: con variables correlacionadas, la variable elegida puede cambiar entre folds. Revisar la estabilidad de la selección o preferir ElasticNet.

---

## 16. Guía rápida de decisión

1. **¿Se espera que la mayoría de las variables aporte algo?** Ridge.
2. **¿Se sospecha que solo unas pocas variables importan y se quiere un modelo interpretable?** Lasso.
3. **¿Hay muchas variables correlacionadas o más variables que ejemplos?** ElasticNet.
4. **¿No está claro?** Validar los tres con los mismos folds y elegir según el error de validación y la simplicidad del modelo.

---

## 17. Ejemplo completo

```python
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

# 1. Datos y conjunto de prueba reservado
X, y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

cv = KFold(n_splits=5, shuffle=True, random_state=42)

# 2. Se agregan términos polinómicos de grado 2 para provocar sobreajuste
#    (de 10 variables se pasa a 65)
def construir(modelo):
    return Pipeline([
        ('poli', PolynomialFeatures(degree=2, include_bias=False)),
        ('esc', StandardScaler()),
        ('modelo', modelo)
    ])

busquedas = {
    'Ridge': GridSearchCV(
        construir(Ridge()),
        {'modelo__alpha': np.logspace(-2, 4, 40)},
        cv=cv, scoring='neg_root_mean_squared_error', n_jobs=-1),
    'Lasso': GridSearchCV(
        construir(Lasso(max_iter=50000)),
        {'modelo__alpha': np.logspace(-3, 1, 40)},
        cv=cv, scoring='neg_root_mean_squared_error', n_jobs=-1),
    'ElasticNet': GridSearchCV(
        construir(ElasticNet(max_iter=50000)),
        {'modelo__alpha': np.logspace(-3, 1, 25),
         'modelo__l1_ratio': [0.1, 0.5, 0.9, 0.99]},
        cv=cv, scoring='neg_root_mean_squared_error', n_jobs=-1),
}

# 3. Línea base sin regularización
base = construir(LinearRegression()).fit(X_train, y_train)
pred = base.predict(X_test)
print(f"{'Lineal':12s} RMSE test={np.sqrt(mean_squared_error(y_test, pred)):7.2f}  "
      f"R2={r2_score(y_test, pred):.3f}")

# 4. Búsqueda y evaluación final de cada modelo regularizado
for nombre, grid in busquedas.items():
    grid.fit(X_train, y_train)
    pred = grid.predict(X_test)
    coefs = grid.best_estimator_.named_steps['modelo'].coef_
    print(f"{nombre:12s} RMSE test={np.sqrt(mean_squared_error(y_test, pred)):7.2f}  "
          f"R2={r2_score(y_test, pred):.3f}  "
          f"variables no nulas={np.sum(coefs != 0)}/{len(coefs)}  "
          f"params={grid.best_params_}")
```

Con 65 variables polinómicas, la regresión lineal sin regularización tiende a sobreajustar y empeora en prueba. Los modelos regularizados, con alpha elegido por validación cruzada, recuperan un buen desempeño; además, Lasso y ElasticNet descartan buena parte de los términos polinómicos y producen un modelo más simple.

SI yo quiero predecir: llueve mañana sí o no?

X (20 variables). y (y variable)

* TP (True Positive / Verdadero Positivo): Casos positivos que el modelo predijo correctamente como positivos. EJEMPLO: el modelo me dijo que mañana llueve y efectivamente es correcto.

* TN (True Negative / Verdadero Negativo): Casos negativos que el modelo predijo correctamente como negativos. EJEMPLO: el modelo predijo que mañana NO llueve y efectivamente no llovió.

* FP (False Positive / Falso Positivo): Casos negativos que el modelo predijo erróneamente como positivos (falsa alarma). EJEMPLO: El modelo afirmó que mañana llueve, pero no llovió.

* FN (False Negative / Falso Negativo): Casos positivos que el modelo predijo erróneamente como negativos (caso omitido). El modelo dijo que mañaana no llueve pero llovió

# Métricas de clasificación en scikit-learn

## 1. Por qué no basta con la exactitud

La métrica más intuitiva para un clasificador es la **exactitud** (accuracy): la proporción de predicciones correctas. Sin embargo, puede ser muy engañosa.

Ejemplo: en un problema de detección de fraude, el 99% de las transacciones son legítimas. Un "modelo" que siempre predice "legítima" obtiene **99% de exactitud** sin detectar un solo fraude.

```python
import numpy as np
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, recall_score

y = np.array([0] * 990 + [1] * 10)        # 1% de casos positivos
X = np.zeros((1000, 1))

dummy = DummyClassifier(strategy='most_frequent').fit(X, y)
y_pred = dummy.predict(X)

print("Exactitud:", accuracy_score(y, y_pred))   # 0.99
print("Recall:   ", recall_score(y, y_pred))     # 0.0, no detecta ningún fraude
```

Por eso se necesitan métricas que distingan **qué tipo de errores** comete el modelo. Todas parten de la matriz de confusión.

Todas las métricas de esta guía están en el módulo `sklearn.metrics`.

---

## 2. Datos de ejemplo y la clase positiva

Se usará el dataset de cáncer de mama. En este dataset la etiqueta 0 corresponde a **maligno** y la 1 a **benigno**. Como lo que interesa detectar es el tumor maligno, se invierten las etiquetas para que **la clase positiva (1) sea maligno**.

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X, y = load_breast_cancer(return_X_y=True)
y = 1 - y   # ahora 1 = maligno (clase positiva), 0 = benigno

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

modelo = Pipeline([
    ('esc', StandardScaler()),
    ('clf', LogisticRegression(max_iter=1000))
])
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)                   # clases predichas (0 o 1)
y_score = modelo.predict_proba(X_test)[:, 1]      # probabilidad de la clase positiva
```

Definir correctamente la **clase positiva** es fundamental: precisión, recall y F1 cambian completamente según cuál sea. En scikit-learn la clase positiva por defecto es `1`; se puede cambiar con el parámetro `pos_label`.

---

## 3. Matriz de confusión

Cruza las clases reales con las predichas. En clasificación binaria tiene cuatro celdas:

|  | **Predicho negativo** | **Predicho positivo** |
|---|---|---|
| **Real negativo** | VN (verdaderos negativos) | FP (falsos positivos) |
| **Real positivo** | FN (falsos negativos) | VP (verdaderos positivos) |

- **FP (error tipo I)**: el modelo dice "positivo" y no lo era. Ejemplo: diagnosticar cáncer a una persona sana.
- **FN (error tipo II)**: el modelo dice "negativo" y sí era positivo. Ejemplo: no detectar un cáncer existente.

```python
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)
print(cm)
# [[VN FP]
#  [FN VP]]

vn, fp, fn, vp = cm.ravel()

ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred, display_labels=['Benigno', 'Maligno']
)
plt.show()
```

En scikit-learn las **filas son las clases reales** y las **columnas las predichas**, ordenadas de menor a mayor etiqueta.

El parámetro `normalize` permite ver proporciones:

| Valor | Normaliza por | Interpretación de cada celda |
|---|---|---|
| `'true'` | Filas | Proporción de cada clase real (la diagonal es el recall) |
| `'pred'` | Columnas | Proporción de cada clase predicha (la diagonal es la precisión) |
| `'all'` | Total | Proporción sobre todos los ejemplos |

---

## 4. Métricas derivadas de la matriz de confusión

### 4.1 Exactitud (accuracy)

$$
\text{Exactitud} = \frac{VP + VN}{VP + VN + FP + FN}
$$

Proporción de predicciones correctas. Adecuada solo con **clases balanceadas** y cuando ambos tipos de error cuestan lo mismo.

### 4.2 Precisión (precision)

$$
\text{Precisión} = \frac{VP}{VP + FP}
$$

De todo lo que el modelo predijo como positivo, qué proporción realmente lo era. Responde: **"cuando el modelo dice positivo, ¿cuánto se puede confiar?"**

Importa cuando los **falsos positivos son costosos**: filtros de spam (no se quiere enviar correos legítimos a spam), recomendaciones, decisiones que implican una intervención cara.

### 4.3 Recall (sensibilidad, tasa de verdaderos positivos)

$$
\text{Recall} = \frac{VP}{VP + FN}
$$

De todos los positivos reales, qué proporción detectó el modelo. Responde: **"¿cuántos de los casos positivos se encontraron?"**

Importa cuando los **falsos negativos son costosos**: diagnóstico médico, detección de fraude, seguridad.

### 4.4 Especificidad (tasa de verdaderos negativos)

$$
\text{Especificidad} = \frac{VN}{VN + FP}
$$

De todos los negativos reales, qué proporción se clasificó correctamente. Es el recall de la clase negativa. scikit-learn no tiene una función dedicada; se calcula con `recall_score(y_test, y_pred, pos_label=0)` o desde la matriz.

### 4.5 Tasa de falsos positivos (FPR)

$$
\text{FPR} = \frac{FP}{FP + VN} = 1 - \text{Especificidad}
$$

Se usa en la curva ROC.

### 4.6 F1-score

$$
F_1 = 2 \cdot \frac{\text{Precisión} \cdot \text{Recall}}{\text{Precisión} + \text{Recall}}
$$

Media **armónica** entre precisión y recall. La media armónica castiga los desequilibrios: si una de las dos es muy baja, F1 también lo es. Útil cuando se quiere un equilibrio entre ambas y hay clases desbalanceadas.

### 4.7 F-beta

$$
F_\beta = (1 + \beta^2) \cdot \frac{\text{Precisión} \cdot \text{Recall}}{\beta^2 \cdot \text{Precisión} + \text{Recall}}
$$

Generaliza F1 dando más peso a una de las dos métricas:

- $\beta > 1$ (por ejemplo, $\beta = 2$): da más importancia al **recall**.
- $\beta < 1$ (por ejemplo, $\beta = 0.5$): da más importancia a la **precisión**.
- $\beta = 1$: equivale a F1.

### 4.8 Exactitud balanceada (balanced accuracy)

$$
\text{Exactitud balanceada} = \frac{\text{Recall} + \text{Especificidad}}{2}
$$

Promedio del recall de cada clase. Un clasificador que siempre predice la clase mayoritaria obtiene 0.5, lo que corrige el problema de la sección 1.

### 4.9 Coeficiente de correlación de Matthews (MCC)

$$
\text{MCC} = \frac{VP \cdot VN - FP \cdot FN}{\sqrt{(VP+FP)(VP+FN)(VN+FP)(VN+FN)}}
$$

Varía entre $-1$ y $1$: 1 es predicción perfecta, 0 equivale al azar y $-1$ es desacuerdo total. Usa las **cuatro celdas** de la matriz, por lo que es una de las métricas más informativas con clases desbalanceadas.

### 4.10 Kappa de Cohen

Mide el acuerdo entre predicciones y valores reales **descontando el acuerdo esperado por azar**. Varía entre $-1$ y $1$. Muy usado cuando se compara con anotadores humanos.

### 4.11 Cálculo en scikit-learn

```python
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             fbeta_score, balanced_accuracy_score,
                             matthews_corrcoef, cohen_kappa_score)

print(f"Exactitud:            {accuracy_score(y_test, y_pred):.3f}")
print(f"Precisión:            {precision_score(y_test, y_pred):.3f}")
print(f"Recall:               {recall_score(y_test, y_pred):.3f}")
print(f"Especificidad:        {recall_score(y_test, y_pred, pos_label=0):.3f}")
print(f"F1:                   {f1_score(y_test, y_pred):.3f}")
print(f"F2:                   {fbeta_score(y_test, y_pred, beta=2):.3f}")
print(f"Exactitud balanceada: {balanced_accuracy_score(y_test, y_pred):.3f}")
print(f"MCC:                  {matthews_corrcoef(y_test, y_pred):.3f}")
print(f"Kappa de Cohen:       {cohen_kappa_score(y_test, y_pred):.3f}")
```

### 4.12 Resumen

| Métrica | Pregunta que responde | Rango | Sensible al desbalance |
|---|---|---|---|
| Exactitud | ¿Qué proporción acierta? | 0 a 1 | Sí (engañosa) |
| Precisión | ¿Cuánto confiar en un "positivo"? | 0 a 1 | Depende de la prevalencia |
| Recall | ¿Cuántos positivos se detectan? | 0 a 1 | No |
| Especificidad | ¿Cuántos negativos se reconocen? | 0 a 1 | No |
| F1 | Equilibrio precisión-recall | 0 a 1 | Ignora los VN |
| Exactitud balanceada | Promedio del recall por clase | 0 a 1 | No |
| MCC | Correlación global predicción-realidad | -1 a 1 | No |
| Kappa | Acuerdo más allá del azar | -1 a 1 | Parcialmente |

---

## 5. classification_report

Resume las métricas principales por clase en una sola tabla:

```python
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=['Benigno', 'Maligno'], digits=3))
```

Salida típica:

```
              precision    recall  f1-score   support

     Benigno      0.978     0.989     0.983        90
     Maligno      0.981     0.962     0.971        53

    accuracy                          0.979       143
   macro avg      0.979     0.976     0.977       143
weighted avg      0.979     0.979     0.979       143
```

- **support**: número de ejemplos reales de cada clase.
- **macro avg** y **weighted avg**: promedios entre clases (ver sección 9).

Con `output_dict=True` devuelve un diccionario, útil para convertirlo en DataFrame.

---

## 6. El umbral de decisión

La mayoría de los clasificadores no predicen directamente una clase, sino un **puntaje** o una **probabilidad**. `predict` aplica un **umbral**, por defecto 0.5:

$$
\hat{y} =
\begin{cases}
1 & \text{si } P(y=1 \mid x) \geq 0.5 \\
0 & \text{en otro caso}
\end{cases}
$$

Cambiar el umbral cambia la matriz de confusión y, por lo tanto, todas las métricas de la sección 4:

- **Umbral bajo**: más predicciones positivas, **sube el recall** y **baja la precisión**.
- **Umbral alto**: menos predicciones positivas, **sube la precisión** y **baja el recall**.

```python
for umbral in [0.1, 0.3, 0.5, 0.7, 0.9]:
    pred_u = (y_score >= umbral).astype(int)
    print(f"umbral={umbral:.1f}  "
          f"precisión={precision_score(y_test, pred_u, zero_division=0):.3f}  "
          f"recall={recall_score(y_test, pred_u):.3f}  "
          f"F1={f1_score(y_test, pred_u):.3f}")
```

Este compromiso entre precisión y recall es la razón de ser de las curvas de las secciones siguientes, que evalúan el modelo en **todos los umbrales posibles**.

Para obtener puntajes se usa `predict_proba` (columna de la clase positiva) o `decision_function` (en modelos como SVM o regresión logística). Las métricas basadas en curvas aceptan cualquiera de los dos.

---

## 7. Curva ROC y AUC

### 7.1 Curva ROC

Grafica la **tasa de verdaderos positivos** (recall) contra la **tasa de falsos positivos** (FPR) para todos los umbrales posibles.

```python
from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay

fpr, tpr, umbrales = roc_curve(y_test, y_score)

RocCurveDisplay.from_predictions(y_test, y_score, name='Regresión logística')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Azar')
plt.legend()
plt.show()
```

Interpretación:

- La **esquina superior izquierda** (FPR = 0, TPR = 1) es el clasificador perfecto.
- La **diagonal** corresponde a un clasificador aleatorio.
- Cuanto más se acerca la curva a la esquina superior izquierda, mejor.

### 7.2 AUC ROC

El **área bajo la curva ROC** resume la curva en un número:

```python
print("AUC ROC:", roc_auc_score(y_test, y_score))
```

| AUC | Interpretación orientativa |
|---|---|
| 0.5 | Equivale al azar |
| 0.7 a 0.8 | Aceptable |
| 0.8 a 0.9 | Bueno |
| Mayor a 0.9 | Excelente |

Interpretación probabilística: el AUC es la **probabilidad de que el modelo asigne un puntaje mayor a un positivo elegido al azar que a un negativo elegido al azar**. Mide la capacidad de **ordenar** (ranking), independiente del umbral.

Importante: `roc_auc_score` debe recibir **puntajes o probabilidades**, no las clases predichas. Pasarle `y_pred` da un valor incorrecto.

### 7.3 Limitación con clases muy desbalanceadas

Con muchos negativos, un aumento grande de falsos positivos produce un cambio pequeño en la FPR (porque el denominador VN + FP es enorme). La curva ROC puede verse muy bien aunque el modelo genere muchas falsas alarmas. En esos casos la curva precisión-recall es más informativa.

---

## 8. Curva precisión-recall y precisión promedio

### 8.1 Curva precisión-recall

Grafica la **precisión** contra el **recall** para todos los umbrales.

```python
from sklearn.metrics import (precision_recall_curve, average_precision_score,
                             PrecisionRecallDisplay)

precision, recall, umbrales_pr = precision_recall_curve(y_test, y_score)

PrecisionRecallDisplay.from_predictions(y_test, y_score, name='Regresión logística')
prevalencia = y_test.mean()
plt.axhline(prevalencia, linestyle='--', color='gray', label=f'Azar ({prevalencia:.2f})')
plt.legend()
plt.show()
```

- El clasificador perfecto está en la **esquina superior derecha**.
- La línea base del azar **no es 0.5**, sino la **proporción de positivos** (prevalencia). Con 1% de positivos, un clasificador aleatorio tiene precisión 0.01.

### 8.2 Precisión promedio (average precision, AP)

Resume la curva PR en un número, como un promedio ponderado de la precisión en cada umbral:

```python
print("Average precision:", average_precision_score(y_test, y_score))
```

### 8.3 ROC vs. precisión-recall

| Aspecto | Curva ROC / AUC | Curva PR / AP |
|---|---|---|
| Ejes | TPR vs. FPR | Precisión vs. recall |
| Línea base del azar | 0.5 | Prevalencia de la clase positiva |
| Usa verdaderos negativos | Sí | No |
| Con clases muy desbalanceadas | Puede ser optimista | Más informativa |
| Foco | Ordenamiento global | Desempeño en la clase positiva |

Regla práctica: con clases balanceadas ambas sirven; cuando la clase positiva es **rara** y es la que interesa, conviene priorizar la curva PR.

---

## 9. Clasificación multiclase

Con más de dos clases, precisión, recall y F1 se calculan **por clase** (cada clase contra el resto) y luego se combinan con el parámetro `average`:

| `average` | Cálculo | Interpretación |
|---|---|---|
| `None` | Devuelve una métrica por clase | Análisis detallado |
| `'macro'` | Promedio simple entre clases | Todas las clases pesan igual, sin importar su tamaño |
| `'weighted'` | Promedio ponderado por el número de ejemplos de cada clase | Refleja la distribución real, puede ocultar clases pequeñas mal clasificadas |
| `'micro'` | Suma VP, FP y FN de todas las clases y calcula la métrica global | En multiclase de una etiqueta, equivale a la exactitud |

```python
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier

Xw, yw = load_wine(return_X_y=True)
Xw_tr, Xw_te, yw_tr, yw_te = train_test_split(Xw, yw, test_size=0.3,
                                              random_state=42, stratify=yw)

rf = RandomForestClassifier(random_state=42).fit(Xw_tr, yw_tr)
yw_pred = rf.predict(Xw_te)
yw_proba = rf.predict_proba(Xw_te)

print("F1 por clase:", f1_score(yw_te, yw_pred, average=None).round(3))
print("F1 macro:    ", round(f1_score(yw_te, yw_pred, average='macro'), 3))
print("F1 weighted: ", round(f1_score(yw_te, yw_pred, average='weighted'), 3))
print("F1 micro:    ", round(f1_score(yw_te, yw_pred, average='micro'), 3))

# AUC multiclase: requiere la matriz de probabilidades completa
print("AUC OvR:", round(roc_auc_score(yw_te, yw_proba, multi_class='ovr'), 3))
print("AUC OvO:", round(roc_auc_score(yw_te, yw_proba, multi_class='ovo'), 3))

ConfusionMatrixDisplay.from_predictions(yw_te, yw_pred)
plt.show()
```

Cuando hay clases minoritarias que importan, **macro** es la opción más exigente, porque un mal desempeño en una clase pequeña baja el promedio tanto como en una grande.

Para AUC multiclase, `multi_class='ovr'` compara cada clase contra el resto y `'ovo'` compara todos los pares de clases.

---

## 10. Métricas probabilísticas

Las métricas anteriores evalúan clases o el ordenamiento de los puntajes. Las siguientes evalúan si las **probabilidades** son buenas en sí mismas.

### 10.1 Log loss (entropía cruzada)

$$
\text{LogLoss} = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(p_i) + (1 - y_i) \log(1 - p_i) \right]
$$

- Penaliza fuertemente las predicciones **muy seguras y equivocadas** (por ejemplo, decir 0.99 cuando la clase real es 0).
- Menor es mejor; 0 es perfecto.
- Es la función de pérdida que optimiza la regresión logística.

### 10.2 Brier score

$$
\text{Brier} = \frac{1}{n} \sum_{i=1}^{n} (p_i - y_i)^2
$$

Error cuadrático medio entre la probabilidad predicha y la clase real. Varía entre 0 (perfecto) y 1. Menos sensible que el log loss a errores extremos.

```python
from sklearn.metrics import log_loss, brier_score_loss

print("Log loss:   ", round(log_loss(y_test, y_score), 4))
print("Brier score:", round(brier_score_loss(y_test, y_score), 4))
```

### 10.3 Calibración

Un modelo está **bien calibrado** si, entre todos los casos a los que asigna probabilidad 0.8, aproximadamente el 80% son realmente positivos. Un modelo puede tener un AUC excelente (ordena bien) y estar mal calibrado (sus probabilidades no son confiables).

```python
from sklearn.calibration import CalibrationDisplay

CalibrationDisplay.from_predictions(y_test, y_score, n_bins=10, name='Regresión logística')
plt.show()
```

La curva de un modelo perfectamente calibrado coincide con la diagonal. Si se necesitan probabilidades confiables (por ejemplo, para estimar riesgo), se puede recalibrar con `CalibratedClassifierCV`.

---

## 11. Elegir el umbral de decisión

El umbral 0.5 rara vez es el óptimo. Debe elegirse según el costo de cada tipo de error, y **con datos de validación**, nunca con el conjunto de prueba.

### 11.1 Umbral que alcanza un recall mínimo

Ejemplo: en diagnóstico se exige detectar al menos el 95% de los tumores malignos, y entre los umbrales que lo logran se quiere la mayor precisión.

```python
from sklearn.model_selection import cross_val_predict, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Probabilidades fuera de muestra en entrenamiento (no se toca el test)
score_val = cross_val_predict(modelo, X_train, y_train, cv=cv, method='predict_proba')[:, 1]

prec, rec, umb = precision_recall_curve(y_train, score_val)
# prec y rec tienen un elemento más que umb; se descarta el último
validos = rec[:-1] >= 0.95
idx = np.argmax(prec[:-1] * validos)
umbral_elegido = umb[idx]

print(f"Umbral elegido: {umbral_elegido:.3f}")

pred_final = (modelo.predict_proba(X_test)[:, 1] >= umbral_elegido).astype(int)
print(classification_report(y_test, pred_final, target_names=['Benigno', 'Maligno']))
```

### 11.2 TunedThresholdClassifierCV

Desde scikit-learn 1.5 existe un estimador que busca el umbral óptimo para una métrica usando validación cruzada:

```python
from sklearn.model_selection import TunedThresholdClassifierCV

modelo_umbral = TunedThresholdClassifierCV(
    modelo,
    scoring='f1',
    cv=cv
)
modelo_umbral.fit(X_train, y_train)

print("Umbral óptimo:", round(modelo_umbral.best_threshold_, 3))
print("F1 test:", round(f1_score(y_test, modelo_umbral.predict(X_test)), 3))
```

Se puede usar con cualquier métrica, incluida una métrica de costo definida con `make_scorer`.

### 11.3 Métrica de costo personalizada

Cuando se conocen los costos reales de cada error, se puede definir una métrica que los refleje:

```python
from sklearn.metrics import make_scorer

def ganancia(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    vn, fp, fn, vp = cm.ravel()
    # Ejemplo: un falso negativo cuesta 10 veces más que un falso positivo
    return -(1 * fp + 10 * fn)

scorer_ganancia = make_scorer(ganancia)

modelo_costo = TunedThresholdClassifierCV(modelo, scoring=scorer_ganancia, cv=cv)
modelo_costo.fit(X_train, y_train)
print("Umbral según costos:", round(modelo_costo.best_threshold_, 3))
```

---

## 12. Uso de métricas en validación cruzada y búsqueda de hiperparámetros

Las métricas se indican con el parámetro `scoring`, mediante un texto o un objeto creado con `make_scorer`.

| Métrica | Valor en `scoring` |
|---|---|
| Exactitud | `'accuracy'` |
| Exactitud balanceada | `'balanced_accuracy'` |
| Precisión | `'precision'`, `'precision_macro'`, `'precision_weighted'` |
| Recall | `'recall'`, `'recall_macro'`, `'recall_weighted'` |
| F1 | `'f1'`, `'f1_macro'`, `'f1_micro'`, `'f1_weighted'` |
| AUC ROC | `'roc_auc'`, `'roc_auc_ovr'`, `'roc_auc_ovo'` |
| Average precision | `'average_precision'` |
| MCC | `'matthews_corrcoef'` |
| Log loss | `'neg_log_loss'` |
| Brier score | `'neg_brier_score'` |
| F-beta | `make_scorer(fbeta_score, beta=2)` |

```python
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer, fbeta_score
import pandas as pd

metricas = {
    'exactitud': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'f2': make_scorer(fbeta_score, beta=2),
    'auc': 'roc_auc',
    'ap': 'average_precision',
    'mcc': 'matthews_corrcoef'
}

res = cross_validate(modelo, X_train, y_train, cv=cv, scoring=metricas)
resumen = pd.DataFrame(res).filter(like='test_')
print(resumen.agg(['mean', 'std']).T.round(3))
```

En `GridSearchCV` se puede usar una métrica o varias; con varias, `refit` indica cuál define el mejor modelo:

```python
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    modelo,
    param_grid={'clf__C': np.logspace(-3, 3, 13)},
    cv=cv,
    scoring={'f1': 'f1', 'recall': 'recall', 'auc': 'roc_auc'},
    refit='recall',
    n_jobs=-1
)
grid.fit(X_train, y_train)
print(grid.best_params_)
```

Las métricas de pérdida (log loss, Brier) llevan el prefijo `neg_` porque scikit-learn siempre **maximiza** el puntaje.

---

## 13. Errores frecuentes

1. **Reportar solo exactitud con clases desbalanceadas.** Siempre complementar con recall, F1, MCC o exactitud balanceada.
2. **Confundir la clase positiva.** Revisar qué etiqueta es 1 y usar `pos_label` si es necesario.
3. **Pasar clases a `roc_auc_score` o `average_precision_score`.** Requieren probabilidades o puntajes.
4. **Elegir el umbral con el conjunto de prueba.** Se elige con validación cruzada sobre entrenamiento y se aplica una sola vez en prueba.
5. **Comparar AP entre datasets con distinta prevalencia.** La línea base de la curva PR depende de la proporción de positivos.
6. **Interpretar F1 como métrica global.** F1 ignora los verdaderos negativos; si estos importan, usar MCC.
7. **Usar `average='micro'` en multiclase pensando que es distinto de la exactitud.** En clasificación multiclase de una etiqueta son equivalentes.
8. **Confiar en las probabilidades sin revisar la calibración.** Un buen AUC no garantiza probabilidades bien calibradas.
9. **Ignorar la advertencia de división por cero en precisión.** Ocurre cuando el modelo no predice ningún positivo; se controla con `zero_division`.

---

## 14. Guía rápida de decisión

| Situación | Métricas recomendadas |
|---|---|
| Clases balanceadas, errores de igual costo | Exactitud, F1, AUC ROC |
| Clases desbalanceadas | Exactitud balanceada, F1, MCC, AP |
| Los falsos negativos son graves (salud, fraude) | Recall, F2, recall con precisión mínima |
| Los falsos positivos son graves (spam, alertas costosas) | Precisión, F0.5 |
| Interesa ordenar casos por riesgo | AUC ROC, AP |
| Se necesitan probabilidades confiables | Log loss, Brier score, curva de calibración |
| Multiclase con clases minoritarias importantes | Métricas con `average='macro'`, matriz de confusión |
| Hay costos conocidos para cada error | Métrica de costo con `make_scorer` y ajuste de umbral |

En la práctica, nunca se reporta una sola métrica: lo habitual es acompañar la matriz de confusión con un pequeño conjunto de métricas elegidas según el problema.

---

## 15. Ejemplo completo

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                     cross_validate, TunedThresholdClassifierCV)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (classification_report, ConfusionMatrixDisplay,
                             RocCurveDisplay, PrecisionRecallDisplay,
                             roc_auc_score, average_precision_score, matthews_corrcoef,
                             make_scorer, fbeta_score)

# 1. Datos: clase positiva = maligno
X, y = load_breast_cancer(return_X_y=True)
y = 1 - y
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 2. Modelos a comparar
modelos = {
    'Reg. logística': Pipeline([('esc', StandardScaler()),
                                ('clf', LogisticRegression(max_iter=1000))]),
    'Árbol (depth=4)': DecisionTreeClassifier(max_depth=4, random_state=42),
}

# 3. Comparación con validación cruzada y varias métricas
metricas = {'exactitud': 'accuracy', 'recall': 'recall', 'precision': 'precision',
            'f1': 'f1', 'f2': make_scorer(fbeta_score, beta=2),
            'auc': 'roc_auc', 'ap': 'average_precision', 'mcc': 'matthews_corrcoef'}

filas = {}
for nombre, m in modelos.items():
    res = cross_validate(m, X_train, y_train, cv=cv, scoring=metricas)
    filas[nombre] = {k.replace('test_', ''): v.mean()
                     for k, v in res.items() if k.startswith('test_')}
print(pd.DataFrame(filas).round(3))

# 4. Ajuste del umbral priorizando recall (F2) para el modelo elegido
elegido = TunedThresholdClassifierCV(
    modelos['Reg. logística'],
    scoring=make_scorer(fbeta_score, beta=2),
    cv=cv
).fit(X_train, y_train)
print("Umbral elegido:", round(elegido.best_threshold_, 3))

# 5. Evaluación final en prueba, una sola vez
y_pred = elegido.predict(X_test)
y_score = elegido.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred, target_names=['Benigno', 'Maligno'], digits=3))
print("AUC ROC:", round(roc_auc_score(y_test, y_score), 3))
print("AP:     ", round(average_precision_score(y_test, y_score), 3))
print("MCC:    ", round(matthews_corrcoef(y_test, y_pred), 3))

# 6. Visualizaciones
fig, ejes = plt.subplots(1, 3, figsize=(18, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred,
                                        display_labels=['Benigno', 'Maligno'], ax=ejes[0])
RocCurveDisplay.from_predictions(y_test, y_score, ax=ejes[1])
PrecisionRecallDisplay.from_predictions(y_test, y_score, ax=ejes[2])
ejes[0].set_title('Matriz de confusión')
ejes[1].set_title('Curva ROC')
ejes[2].set_title('Curva precisión-recall')
plt.tight_layout()
plt.show()
```

El flujo resume la lógica de la guía: se comparan modelos con varias métricas mediante validación cruzada, se ajusta el umbral según el costo de los errores (aquí, priorizando no dejar tumores malignos sin detectar), y se reporta el desempeño final en prueba con métricas complementarias y sus gráficos.

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO6AOtt0_lYRsVIOYJ793QX416eBscZW2xrPWuO0nCV09_aRXoIOE9loU0&s=10)

# Métricas de clasificación en scikit-learn

## 1. Por qué no basta con la exactitud

La métrica más intuitiva para un clasificador es la **exactitud** (accuracy): la proporción de predicciones correctas. Sin embargo, puede ser muy engañosa.

Ejemplo: en un problema de detección de fraude, el 99% de las transacciones son legítimas. Un "modelo" que siempre predice "legítima" obtiene **99% de exactitud** sin detectar un solo fraude.

```python
import numpy as np
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, recall_score

y = np.array([0] * 990 + [1] * 10)        # 1% de casos positivos
X = np.zeros((1000, 1))

dummy = DummyClassifier(strategy='most_frequent').fit(X, y)
y_pred = dummy.predict(X)

print("Exactitud:", accuracy_score(y, y_pred))   # 0.99
print("Recall:   ", recall_score(y, y_pred))     # 0.0, no detecta ningún fraude
```

Por eso se necesitan métricas que distingan **qué tipo de errores** comete el modelo. Todas parten de la matriz de confusión.

Todas las métricas de esta guía están en el módulo `sklearn.metrics`.

---

## 2. Datos de ejemplo y la clase positiva

Se usará el dataset de cáncer de mama. En este dataset la etiqueta 0 corresponde a **maligno** y la 1 a **benigno**. Como lo que interesa detectar es el tumor maligno, se invierten las etiquetas para que **la clase positiva (1) sea maligno**.

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X, y = load_breast_cancer(return_X_y=True)
y = 1 - y   # ahora 1 = maligno (clase positiva), 0 = benigno

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

modelo = Pipeline([
    ('esc', StandardScaler()),
    ('clf', LogisticRegression(max_iter=1000))
])
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)                   # clases predichas (0 o 1)
y_score = modelo.predict_proba(X_test)[:, 1]      # probabilidad de la clase positiva
```

Definir correctamente la **clase positiva** es fundamental: precisión, recall y F1 cambian completamente según cuál sea. En scikit-learn la clase positiva por defecto es `1`; se puede cambiar con el parámetro `pos_label`.

---

## 3. Matriz de confusión

Cruza las clases reales con las predichas. En clasificación binaria tiene cuatro celdas:

|  | **Predicho negativo** | **Predicho positivo** |
|---|---|---|
| **Real negativo** | VN (verdaderos negativos) | FP (falsos positivos) |
| **Real positivo** | FN (falsos negativos) | VP (verdaderos positivos) |

- **FP (error tipo I)**: el modelo dice "positivo" y no lo era. Ejemplo: diagnosticar cáncer a una persona sana.
- **FN (error tipo II)**: el modelo dice "negativo" y sí era positivo. Ejemplo: no detectar un cáncer existente.

```python
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)
print(cm)
# [[VN FP]
#  [FN VP]]

vn, fp, fn, vp = cm.ravel()

ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred, display_labels=['Benigno', 'Maligno']
)
plt.show()
```

En scikit-learn las **filas son las clases reales** y las **columnas las predichas**, ordenadas de menor a mayor etiqueta.

El parámetro `normalize` permite ver proporciones:

| Valor | Normaliza por | Interpretación de cada celda |
|---|---|---|
| `'true'` | Filas | Proporción de cada clase real (la diagonal es el recall) |
| `'pred'` | Columnas | Proporción de cada clase predicha (la diagonal es la precisión) |
| `'all'` | Total | Proporción sobre todos los ejemplos |

---

## 4. Métricas derivadas de la matriz de confusión

### 4.1 Exactitud (accuracy)

$$
\text{Exactitud} = \frac{VP + VN}{VP + VN + FP + FN}
$$

Proporción de predicciones correctas. Adecuada solo con **clases balanceadas** y cuando ambos tipos de error cuestan lo mismo.

### 4.2 Precisión (precision)

$$
\text{Precisión} = \frac{VP}{VP + FP}
$$

De todo lo que el modelo predijo como positivo, qué proporción realmente lo era. Responde: **"cuando el modelo dice positivo, ¿cuánto se puede confiar?"**

Importa cuando los **falsos positivos son costosos**: filtros de spam (no se quiere enviar correos legítimos a spam), recomendaciones, decisiones que implican una intervención cara.

### 4.3 Recall (sensibilidad, tasa de verdaderos positivos)

$$
\text{Recall} = \frac{VP}{VP + FN}
$$

De todos los positivos reales, qué proporción detectó el modelo. Responde: **"¿cuántos de los casos positivos se encontraron?"**

Importa cuando los **falsos negativos son costosos**: diagnóstico médico, detección de fraude, seguridad.

### 4.4 Especificidad (tasa de verdaderos negativos)

$$
\text{Especificidad} = \frac{VN}{VN + FP}
$$

De todos los negativos reales, qué proporción se clasificó correctamente. Es el recall de la clase negativa. scikit-learn no tiene una función dedicada; se calcula con `recall_score(y_test, y_pred, pos_label=0)` o desde la matriz.

### 4.5 Tasa de falsos positivos (FPR)

$$
\text{FPR} = \frac{FP}{FP + VN} = 1 - \text{Especificidad}
$$

Se usa en la curva ROC.

### 4.6 F1-score

$$
F_1 = 2 \cdot \frac{\text{Precisión} \cdot \text{Recall}}{\text{Precisión} + \text{Recall}}
$$

Media **armónica** entre precisión y recall. La media armónica castiga los desequilibrios: si una de las dos es muy baja, F1 también lo es. Útil cuando se quiere un equilibrio entre ambas y hay clases desbalanceadas.

### 4.7 F-beta

$$
F_\beta = (1 + \beta^2) \cdot \frac{\text{Precisión} \cdot \text{Recall}}{\beta^2 \cdot \text{Precisión} + \text{Recall}}
$$

Generaliza F1 dando más peso a una de las dos métricas:

- $\beta > 1$ (por ejemplo, $\beta = 2$): da más importancia al **recall**.
- $\beta < 1$ (por ejemplo, $\beta = 0.5$): da más importancia a la **precisión**.
- $\beta = 1$: equivale a F1.

### 4.8 Exactitud balanceada (balanced accuracy)

$$
\text{Exactitud balanceada} = \frac{\text{Recall} + \text{Especificidad}}{2}
$$

Promedio del recall de cada clase. Un clasificador que siempre predice la clase mayoritaria obtiene 0.5, lo que corrige el problema de la sección 1.

### 4.9 Coeficiente de correlación de Matthews (MCC)

$$
\text{MCC} = \frac{VP \cdot VN - FP \cdot FN}{\sqrt{(VP+FP)(VP+FN)(VN+FP)(VN+FN)}}
$$

Varía entre $-1$ y $1$: 1 es predicción perfecta, 0 equivale al azar y $-1$ es desacuerdo total. Usa las **cuatro celdas** de la matriz, por lo que es una de las métricas más informativas con clases desbalanceadas.

### 4.10 Kappa de Cohen

Mide el acuerdo entre predicciones y valores reales **descontando el acuerdo esperado por azar**. Varía entre $-1$ y $1$. Muy usado cuando se compara con anotadores humanos.

### 4.11 Cálculo en scikit-learn

```python
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             fbeta_score, balanced_accuracy_score,
                             matthews_corrcoef, cohen_kappa_score)

print(f"Exactitud:            {accuracy_score(y_test, y_pred):.3f}")
print(f"Precisión:            {precision_score(y_test, y_pred):.3f}")
print(f"Recall:               {recall_score(y_test, y_pred):.3f}")
print(f"Especificidad:        {recall_score(y_test, y_pred, pos_label=0):.3f}")
print(f"F1:                   {f1_score(y_test, y_pred):.3f}")
print(f"F2:                   {fbeta_score(y_test, y_pred, beta=2):.3f}")
print(f"Exactitud balanceada: {balanced_accuracy_score(y_test, y_pred):.3f}")
print(f"MCC:                  {matthews_corrcoef(y_test, y_pred):.3f}")
print(f"Kappa de Cohen:       {cohen_kappa_score(y_test, y_pred):.3f}")
```

### 4.12 Resumen

| Métrica | Pregunta que responde | Rango | Sensible al desbalance |
|---|---|---|---|
| Exactitud | ¿Qué proporción acierta? | 0 a 1 | Sí (engañosa) |
| Precisión | ¿Cuánto confiar en un "positivo"? | 0 a 1 | Depende de la prevalencia |
| Recall | ¿Cuántos positivos se detectan? | 0 a 1 | No |
| Especificidad | ¿Cuántos negativos se reconocen? | 0 a 1 | No |
| F1 | Equilibrio precisión-recall | 0 a 1 | Ignora los VN |
| Exactitud balanceada | Promedio del recall por clase | 0 a 1 | No |
| MCC | Correlación global predicción-realidad | -1 a 1 | No |
| Kappa | Acuerdo más allá del azar | -1 a 1 | Parcialmente |

---

## 5. classification_report

Resume las métricas principales por clase en una sola tabla:

```python
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names=['Benigno', 'Maligno'], digits=3))
```

Salida típica:

```
              precision    recall  f1-score   support

     Benigno      0.978     0.989     0.983        90
     Maligno      0.981     0.962     0.971        53

    accuracy                          0.979       143
   macro avg      0.979     0.976     0.977       143
weighted avg      0.979     0.979     0.979       143
```

- **support**: número de ejemplos reales de cada clase.
- **macro avg** y **weighted avg**: promedios entre clases (ver sección 9).

Con `output_dict=True` devuelve un diccionario, útil para convertirlo en DataFrame.

---

## 6. El umbral de decisión

La mayoría de los clasificadores no predicen directamente una clase, sino un **puntaje** o una **probabilidad**. `predict` aplica un **umbral**, por defecto 0.5:

$$
\hat{y} =
\begin{cases}
1 & \text{si } P(y=1 \mid x) \geq 0.5 \\
0 & \text{en otro caso}
\end{cases}
$$

Cambiar el umbral cambia la matriz de confusión y, por lo tanto, todas las métricas de la sección 4:

- **Umbral bajo**: más predicciones positivas, **sube el recall** y **baja la precisión**.
- **Umbral alto**: menos predicciones positivas, **sube la precisión** y **baja el recall**.

```python
for umbral in [0.1, 0.3, 0.5, 0.7, 0.9]:
    pred_u = (y_score >= umbral).astype(int)
    print(f"umbral={umbral:.1f}  "
          f"precisión={precision_score(y_test, pred_u, zero_division=0):.3f}  "
          f"recall={recall_score(y_test, pred_u):.3f}  "
          f"F1={f1_score(y_test, pred_u):.3f}")
```

Este compromiso entre precisión y recall es la razón de ser de las curvas de las secciones siguientes, que evalúan el modelo en **todos los umbrales posibles**.

Para obtener puntajes se usa `predict_proba` (columna de la clase positiva) o `decision_function` (en modelos como SVM o regresión logística). Las métricas basadas en curvas aceptan cualquiera de los dos.

---

## 7. Curva ROC y AUC

### 7.1 Curva ROC

Grafica la **tasa de verdaderos positivos** (recall) contra la **tasa de falsos positivos** (FPR) para todos los umbrales posibles.

```python
from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay

fpr, tpr, umbrales = roc_curve(y_test, y_score)

RocCurveDisplay.from_predictions(y_test, y_score, name='Regresión logística')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Azar')
plt.legend()
plt.show()
```

Interpretación:

- La **esquina superior izquierda** (FPR = 0, TPR = 1) es el clasificador perfecto.
- La **diagonal** corresponde a un clasificador aleatorio.
- Cuanto más se acerca la curva a la esquina superior izquierda, mejor.

### 7.2 AUC ROC

El **área bajo la curva ROC** resume la curva en un número:

```python
print("AUC ROC:", roc_auc_score(y_test, y_score))
```

| AUC | Interpretación orientativa |
|---|---|
| 0.5 | Equivale al azar |
| 0.7 a 0.8 | Aceptable |
| 0.8 a 0.9 | Bueno |
| Mayor a 0.9 | Excelente |

Interpretación probabilística: el AUC es la **probabilidad de que el modelo asigne un puntaje mayor a un positivo elegido al azar que a un negativo elegido al azar**. Mide la capacidad de **ordenar** (ranking), independiente del umbral.

Importante: `roc_auc_score` debe recibir **puntajes o probabilidades**, no las clases predichas. Pasarle `y_pred` da un valor incorrecto.

### 7.3 Limitación con clases muy desbalanceadas

Con muchos negativos, un aumento grande de falsos positivos produce un cambio pequeño en la FPR (porque el denominador VN + FP es enorme). La curva ROC puede verse muy bien aunque el modelo genere muchas falsas alarmas. En esos casos la curva precisión-recall es más informativa.

---

## 8. Curva precisión-recall y precisión promedio

### 8.1 Curva precisión-recall

Grafica la **precisión** contra el **recall** para todos los umbrales.

```python
from sklearn.metrics import (precision_recall_curve, average_precision_score,
                             PrecisionRecallDisplay)

precision, recall, umbrales_pr = precision_recall_curve(y_test, y_score)

PrecisionRecallDisplay.from_predictions(y_test, y_score, name='Regresión logística')
prevalencia = y_test.mean()
plt.axhline(prevalencia, linestyle='--', color='gray', label=f'Azar ({prevalencia:.2f})')
plt.legend()
plt.show()
```

- El clasificador perfecto está en la **esquina superior derecha**.
- La línea base del azar **no es 0.5**, sino la **proporción de positivos** (prevalencia). Con 1% de positivos, un clasificador aleatorio tiene precisión 0.01.

### 8.2 Precisión promedio (average precision, AP)

Resume la curva PR en un número, como un promedio ponderado de la precisión en cada umbral:

```python
print("Average precision:", average_precision_score(y_test, y_score))
```

### 8.3 ROC vs. precisión-recall

| Aspecto | Curva ROC / AUC | Curva PR / AP |
|---|---|---|
| Ejes | TPR vs. FPR | Precisión vs. recall |
| Línea base del azar | 0.5 | Prevalencia de la clase positiva |
| Usa verdaderos negativos | Sí | No |
| Con clases muy desbalanceadas | Puede ser optimista | Más informativa |
| Foco | Ordenamiento global | Desempeño en la clase positiva |

Regla práctica: con clases balanceadas ambas sirven; cuando la clase positiva es **rara** y es la que interesa, conviene priorizar la curva PR.

---

## 9. Clasificación multiclase

Con más de dos clases, precisión, recall y F1 se calculan **por clase** (cada clase contra el resto) y luego se combinan con el parámetro `average`:

| `average` | Cálculo | Interpretación |
|---|---|---|
| `None` | Devuelve una métrica por clase | Análisis detallado |
| `'macro'` | Promedio simple entre clases | Todas las clases pesan igual, sin importar su tamaño |
| `'weighted'` | Promedio ponderado por el número de ejemplos de cada clase | Refleja la distribución real, puede ocultar clases pequeñas mal clasificadas |
| `'micro'` | Suma VP, FP y FN de todas las clases y calcula la métrica global | En multiclase de una etiqueta, equivale a la exactitud |

```python
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier

Xw, yw = load_wine(return_X_y=True)
Xw_tr, Xw_te, yw_tr, yw_te = train_test_split(Xw, yw, test_size=0.3,
                                              random_state=42, stratify=yw)

rf = RandomForestClassifier(random_state=42).fit(Xw_tr, yw_tr)
yw_pred = rf.predict(Xw_te)
yw_proba = rf.predict_proba(Xw_te)

print("F1 por clase:", f1_score(yw_te, yw_pred, average=None).round(3))
print("F1 macro:    ", round(f1_score(yw_te, yw_pred, average='macro'), 3))
print("F1 weighted: ", round(f1_score(yw_te, yw_pred, average='weighted'), 3))
print("F1 micro:    ", round(f1_score(yw_te, yw_pred, average='micro'), 3))

# AUC multiclase: requiere la matriz de probabilidades completa
print("AUC OvR:", round(roc_auc_score(yw_te, yw_proba, multi_class='ovr'), 3))
print("AUC OvO:", round(roc_auc_score(yw_te, yw_proba, multi_class='ovo'), 3))

ConfusionMatrixDisplay.from_predictions(yw_te, yw_pred)
plt.show()
```

Cuando hay clases minoritarias que importan, **macro** es la opción más exigente, porque un mal desempeño en una clase pequeña baja el promedio tanto como en una grande.

Para AUC multiclase, `multi_class='ovr'` compara cada clase contra el resto y `'ovo'` compara todos los pares de clases.

---

## 10. Métricas probabilísticas

Las métricas anteriores evalúan clases o el ordenamiento de los puntajes. Las siguientes evalúan si las **probabilidades** son buenas en sí mismas.

### 10.1 Log loss (entropía cruzada)

$$
\text{LogLoss} = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(p_i) + (1 - y_i) \log(1 - p_i) \right]
$$

- Penaliza fuertemente las predicciones **muy seguras y equivocadas** (por ejemplo, decir 0.99 cuando la clase real es 0).
- Menor es mejor; 0 es perfecto.
- Es la función de pérdida que optimiza la regresión logística.

### 10.2 Brier score

$$
\text{Brier} = \frac{1}{n} \sum_{i=1}^{n} (p_i - y_i)^2
$$

Error cuadrático medio entre la probabilidad predicha y la clase real. Varía entre 0 (perfecto) y 1. Menos sensible que el log loss a errores extremos.

```python
from sklearn.metrics import log_loss, brier_score_loss

print("Log loss:   ", round(log_loss(y_test, y_score), 4))
print("Brier score:", round(brier_score_loss(y_test, y_score), 4))
```

### 10.3 Calibración

Un modelo está **bien calibrado** si, entre todos los casos a los que asigna probabilidad 0.8, aproximadamente el 80% son realmente positivos. Un modelo puede tener un AUC excelente (ordena bien) y estar mal calibrado (sus probabilidades no son confiables).

```python
from sklearn.calibration import CalibrationDisplay

CalibrationDisplay.from_predictions(y_test, y_score, n_bins=10, name='Regresión logística')
plt.show()
```

La curva de un modelo perfectamente calibrado coincide con la diagonal. Si se necesitan probabilidades confiables (por ejemplo, para estimar riesgo), se puede recalibrar con `CalibratedClassifierCV`.

---

## 11. Elegir el umbral de decisión

El umbral 0.5 rara vez es el óptimo. Debe elegirse según el costo de cada tipo de error, y **con datos de validación**, nunca con el conjunto de prueba.

### 11.1 Umbral que alcanza un recall mínimo

Ejemplo: en diagnóstico se exige detectar al menos el 95% de los tumores malignos, y entre los umbrales que lo logran se quiere la mayor precisión.

```python
from sklearn.model_selection import cross_val_predict, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Probabilidades fuera de muestra en entrenamiento (no se toca el test)
score_val = cross_val_predict(modelo, X_train, y_train, cv=cv, method='predict_proba')[:, 1]

prec, rec, umb = precision_recall_curve(y_train, score_val)
# prec y rec tienen un elemento más que umb; se descarta el último
validos = rec[:-1] >= 0.95
idx = np.argmax(prec[:-1] * validos)
umbral_elegido = umb[idx]

print(f"Umbral elegido: {umbral_elegido:.3f}")

pred_final = (modelo.predict_proba(X_test)[:, 1] >= umbral_elegido).astype(int)
print(classification_report(y_test, pred_final, target_names=['Benigno', 'Maligno']))
```

### 11.2 TunedThresholdClassifierCV

Desde scikit-learn 1.5 existe un estimador que busca el umbral óptimo para una métrica usando validación cruzada:

```python
from sklearn.model_selection import TunedThresholdClassifierCV

modelo_umbral = TunedThresholdClassifierCV(
    modelo,
    scoring='f1',
    cv=cv
)
modelo_umbral.fit(X_train, y_train)

print("Umbral óptimo:", round(modelo_umbral.best_threshold_, 3))
print("F1 test:", round(f1_score(y_test, modelo_umbral.predict(X_test)), 3))
```

Se puede usar con cualquier métrica, incluida una métrica de costo definida con `make_scorer`.

### 11.3 Métrica de costo personalizada

Cuando se conocen los costos reales de cada error, se puede definir una métrica que los refleje:

```python
from sklearn.metrics import make_scorer

def ganancia(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    vn, fp, fn, vp = cm.ravel()
    # Ejemplo: un falso negativo cuesta 10 veces más que un falso positivo
    return -(1 * fp + 10 * fn)

scorer_ganancia = make_scorer(ganancia)

modelo_costo = TunedThresholdClassifierCV(modelo, scoring=scorer_ganancia, cv=cv)
modelo_costo.fit(X_train, y_train)
print("Umbral según costos:", round(modelo_costo.best_threshold_, 3))
```

---

## 12. Uso de métricas en validación cruzada y búsqueda de hiperparámetros

Las métricas se indican con el parámetro `scoring`, mediante un texto o un objeto creado con `make_scorer`.

| Métrica | Valor en `scoring` |
|---|---|
| Exactitud | `'accuracy'` |
| Exactitud balanceada | `'balanced_accuracy'` |
| Precisión | `'precision'`, `'precision_macro'`, `'precision_weighted'` |
| Recall | `'recall'`, `'recall_macro'`, `'recall_weighted'` |
| F1 | `'f1'`, `'f1_macro'`, `'f1_micro'`, `'f1_weighted'` |
| AUC ROC | `'roc_auc'`, `'roc_auc_ovr'`, `'roc_auc_ovo'` |
| Average precision | `'average_precision'` |
| MCC | `'matthews_corrcoef'` |
| Log loss | `'neg_log_loss'` |
| Brier score | `'neg_brier_score'` |
| F-beta | `make_scorer(fbeta_score, beta=2)` |

```python
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer, fbeta_score
import pandas as pd

metricas = {
    'exactitud': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'f2': make_scorer(fbeta_score, beta=2),
    'auc': 'roc_auc',
    'ap': 'average_precision',
    'mcc': 'matthews_corrcoef'
}

res = cross_validate(modelo, X_train, y_train, cv=cv, scoring=metricas)
resumen = pd.DataFrame(res).filter(like='test_')
print(resumen.agg(['mean', 'std']).T.round(3))
```

En `GridSearchCV` se puede usar una métrica o varias; con varias, `refit` indica cuál define el mejor modelo:

```python
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    modelo,
    param_grid={'clf__C': np.logspace(-3, 3, 13)},
    cv=cv,
    scoring={'f1': 'f1', 'recall': 'recall', 'auc': 'roc_auc'},
    refit='recall',
    n_jobs=-1
)
grid.fit(X_train, y_train)
print(grid.best_params_)
```

Las métricas de pérdida (log loss, Brier) llevan el prefijo `neg_` porque scikit-learn siempre **maximiza** el puntaje.

---

## 13. Errores frecuentes

1. **Reportar solo exactitud con clases desbalanceadas.** Siempre complementar con recall, F1, MCC o exactitud balanceada.
2. **Confundir la clase positiva.** Revisar qué etiqueta es 1 y usar `pos_label` si es necesario.
3. **Pasar clases a `roc_auc_score` o `average_precision_score`.** Requieren probabilidades o puntajes.
4. **Elegir el umbral con el conjunto de prueba.** Se elige con validación cruzada sobre entrenamiento y se aplica una sola vez en prueba.
5. **Comparar AP entre datasets con distinta prevalencia.** La línea base de la curva PR depende de la proporción de positivos.
6. **Interpretar F1 como métrica global.** F1 ignora los verdaderos negativos; si estos importan, usar MCC.
7. **Usar `average='micro'` en multiclase pensando que es distinto de la exactitud.** En clasificación multiclase de una etiqueta son equivalentes.
8. **Confiar en las probabilidades sin revisar la calibración.** Un buen AUC no garantiza probabilidades bien calibradas.
9. **Ignorar la advertencia de división por cero en precisión.** Ocurre cuando el modelo no predice ningún positivo; se controla con `zero_division`.

---

## 14. Guía rápida de decisión

| Situación | Métricas recomendadas |
|---|---|
| Clases balanceadas, errores de igual costo | Exactitud, F1, AUC ROC |
| Clases desbalanceadas | Exactitud balanceada, F1, MCC, AP |
| Los falsos negativos son graves (salud, fraude) | Recall, F2, recall con precisión mínima |
| Los falsos positivos son graves (spam, alertas costosas) | Precisión, F0.5 |
| Interesa ordenar casos por riesgo | AUC ROC, AP |
| Se necesitan probabilidades confiables | Log loss, Brier score, curva de calibración |
| Multiclase con clases minoritarias importantes | Métricas con `average='macro'`, matriz de confusión |
| Hay costos conocidos para cada error | Métrica de costo con `make_scorer` y ajuste de umbral |

En la práctica, nunca se reporta una sola métrica: lo habitual es acompañar la matriz de confusión con un pequeño conjunto de métricas elegidas según el problema.

---

## 15. Ejemplo completo

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                     cross_validate, TunedThresholdClassifierCV)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (classification_report, ConfusionMatrixDisplay,
                             RocCurveDisplay, PrecisionRecallDisplay,
                             roc_auc_score, average_precision_score, matthews_corrcoef,
                             make_scorer, fbeta_score)

# 1. Datos: clase positiva = maligno
X, y = load_breast_cancer(return_X_y=True)
y = 1 - y
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 2. Modelos a comparar
modelos = {
    'Reg. logística': Pipeline([('esc', StandardScaler()),
                                ('clf', LogisticRegression(max_iter=1000))]),
    'Árbol (depth=4)': DecisionTreeClassifier(max_depth=4, random_state=42),
}

# 3. Comparación con validación cruzada y varias métricas
metricas = {'exactitud': 'accuracy', 'recall': 'recall', 'precision': 'precision',
            'f1': 'f1', 'f2': make_scorer(fbeta_score, beta=2),
            'auc': 'roc_auc', 'ap': 'average_precision', 'mcc': 'matthews_corrcoef'}

filas = {}
for nombre, m in modelos.items():
    res = cross_validate(m, X_train, y_train, cv=cv, scoring=metricas)
    filas[nombre] = {k.replace('test_', ''): v.mean()
                     for k, v in res.items() if k.startswith('test_')}
print(pd.DataFrame(filas).round(3))

# 4. Ajuste del umbral priorizando recall (F2) para el modelo elegido
elegido = TunedThresholdClassifierCV(
    modelos['Reg. logística'],
    scoring=make_scorer(fbeta_score, beta=2),
    cv=cv
).fit(X_train, y_train)
print("Umbral elegido:", round(elegido.best_threshold_, 3))

# 5. Evaluación final en prueba, una sola vez
y_pred = elegido.predict(X_test)
y_score = elegido.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred, target_names=['Benigno', 'Maligno'], digits=3))
print("AUC ROC:", round(roc_auc_score(y_test, y_score), 3))
print("AP:     ", round(average_precision_score(y_test, y_score), 3))
print("MCC:    ", round(matthews_corrcoef(y_test, y_pred), 3))

# 6. Visualizaciones
fig, ejes = plt.subplots(1, 3, figsize=(18, 5))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred,
                                        display_labels=['Benigno', 'Maligno'], ax=ejes[0])
RocCurveDisplay.from_predictions(y_test, y_score, ax=ejes[1])
PrecisionRecallDisplay.from_predictions(y_test, y_score, ax=ejes[2])
ejes[0].set_title('Matriz de confusión')
ejes[1].set_title('Curva ROC')
ejes[2].set_title('Curva precisión-recall')
plt.tight_layout()
plt.show()
```

El flujo resume la lógica de la guía: se comparan modelos con varias métricas mediante validación cruzada, se ajusta el umbral según el costo de los errores (aquí, priorizando no dejar tumores malignos sin detectar), y se reporta el desempeño final en prueba con métricas complementarias y sus gráficos.

# SIC 2026 · Inteligencia Artificial
## Clase 3: Ustedes enseñan el Capítulo 5 (Machine Learning supervisado)

**Samsung Innovation Campus Chile 2026 · ONG Innovacien**

Hoy la clase la dan ustedes. El curso se divide en tres grupos y cada uno se hace cargo de una parte del **Capítulo 5: Machine Learning 1, aprendizaje supervisado**. Cada grupo prepara una explicación de los conceptos centrales y la muestra con **ejemplos prácticos creados por ustedes**, no copiados de las láminas.

**Presentación del Capítulo 5:** [abrir en Google Drive](https://drive.google.com/file/d/1pcJHh13Ra2yuhA-vyDja2Z-sAfXGO_y9/view?usp=drive_link)

| Grupo | Láminas | Tema |
|---|---|---|
| **Grupo 1** | 14 a 194 | Unidad 1: fundamentos de ML con scikit-learn, datos, preprocesamiento, optimización y métricas |
| **Grupo 2** | 195 a 314 | Unidades 2 y 3: regresión lineal y regresión logística |
| **Grupo 3** | 315 al final | Unidades 4 a 8: árbol de decisión, Naive Bayes, KNN, SVM y ensambles |

El Grupo 1 es el más grande porque su parte es la base de todo lo demás: si la clase no entiende bien `fit`, la división de datos o las métricas, el resto no se sostiene.

---
# Parte 0. Cómo funciona la clase

## Agenda

| Hora | Actividad |
|---|---|
| 18:00 a 18:15 | Explicación de la dinámica y formación de grupos |
| 18:15 a 19:15 | Preparación en grupos (salas separadas en Meet) |
| 19:15 a 20:15 | Presenta el **Grupo 1** |
| 20:15 a 20:25 | Pausa |
| 20:25 a 21:05 | Presenta el **Grupo 2** |
| 21:05 a 21:45 | Presenta el **Grupo 3** |
| 21:45 a 22:00 | Cierre y preguntas de repaso |

## Organización

Cada grupo se divide en **subgrupos de 2 o 3 personas**, uno por bloque de láminas. Cada subgrupo presenta **10 a 12 minutos**:

1. **Explicación (4 a 5 min):** los conceptos centrales con sus propias palabras. No lean las láminas.
2. **Ejemplo propio (4 a 5 min):** código que ustedes escribieron, ejecutado en vivo, con un dataset distinto al de las láminas cuando sea posible.
3. **Ejercicio para la clase (2 min):** un ejercicio corto que sus compañeros resuelven en este mismo notebook, con su celda de verificación.

## Qué tiene cada sección de este notebook

- **Láminas** que les corresponden y **conceptos que deben explicar** (es la lista mínima).
- **Preguntas que la clase debe poder responder** después de su presentación. Úsenlas para revisar si su explicación quedó completa.
- **Material de reserva:** notebooks de ejercicios y datos del capítulo que pueden usar como punto de partida.
- **Kit de inicio:** una celda que ya funciona, para que no partan de cero. Modifíquenla, amplíenla o reemplácenla.
- **Espacios para su explicación, su ejemplo y su ejercicio.**

## Qué se considera una buena presentación

| Criterio | Qué significa |
|---|---|
| Conceptos claros | Explican el porqué, no solo el cómo. Usan ejemplos cotidianos. |
| Ejemplo propio | El código es de ustedes, funciona y muestra el concepto. |
| Ejercicio para la clase | Es corto, se puede resolver en 2 minutos y tiene verificación. |
| Tiempo | Respetan los 10 a 12 minutos del subgrupo. |

**Al terminar**, guarden el notebook de su grupo en el repositorio con *Archivo > Guardar una copia en GitHub*, en la carpeta `ejercicios_estudiantes`, con el nombre `clase03_grupo1A_apellidos.ipynb` (cambiando el subgrupo).

## Preparación del entorno

Ejecuten esta celda. Importa las librerías, define la función `revisar` (la misma de la Clase 2) y una función `cargar_csv` para los datos de reserva del capítulo.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

def revisar(condicion, mensaje_ok="Correcto.", mensaje_error="Todavía no. Revisa tu respuesta."):
    """Imprime si un ejercicio está bien resuelto."""
    try:
        print(mensaje_ok if condicion() else mensaje_error)
    except Exception:
        print(mensaje_error)

URL_DATOS = "https://raw.githubusercontent.com/davidlealo/sic_ia_2026/main/datos/cap05/"

def cargar_csv(nombre):
    """Carga un CSV de reserva del capítulo 5: primero desde el repositorio y, si no está, desde los archivos subidos a Colab."""
    try:
        return pd.read_csv(URL_DATOS + nombre)
    except Exception:
        try:
            return pd.read_csv(nombre)
        except FileNotFoundError:
            print(f"No encontré {nombre}. Súbelo con el ícono de carpeta de la izquierda o con:")
            print("from google.colab import files; files.upload()")

print("Listo.")

**Datos de reserva del capítulo** (también están en la carpeta del curso en Drive):

| Archivo | Contenido | Sirve para |
|---|---|---|
| `data_Iris.csv` | Medidas de flores iris y su especie | Clasificación, EDA (Grupo 1) |
| `data_galton.csv` | Estatura de padres e hijos | Regresión lineal simple |
| `TV_Sales.csv` | Ventas de televisores según precio, ingreso y ubicación | Regresión múltiple, diagnóstico, árboles |
| `data_studentlist.csv` | Estudiantes con género, edad, estatura y peso | Variables dummy e interacción |
| `data_mtcars.csv` | Características de 32 autos | Ridge y Lasso |
| `data_titanic.csv` | Titanic original con nombres, cabina y faltantes | Faltantes, preprocesamiento, KNN |
| `data_titanic_2.csv` | Titanic ya preprocesado | Árboles, KNN |

También pueden usar los datasets incluidos en librerías, que no requieren descargar nada: en scikit-learn `load_wine`, `load_breast_cancer`, `load_diabetes`, `load_digits`, `make_moons`; en seaborn `penguins`, `tips`, `mpg`, `diamonds`. **Usar un dataset distinto al de las láminas es la mejor forma de demostrar que entendieron.**

---
# Grupo 1. Fundamentos de machine learning con scikit-learn (láminas 14 a 194)

Esta es la Unidad 1 del capítulo y la base de todo lo que viene. Se divide en cuatro subgrupos:

| Subgrupo | Láminas | Tema |
|---|---|---|
| 1A | 14 a 47 | Parámetros e hiperparámetros, la API de scikit-learn |
| 1B | 48 a 112 | División de datos, sobreajuste, validación cruzada y preprocesamiento |
| 1C | 113 a 171 | Regularización y cómo encontrar el mejor modelo (caso iris) |
| 1D | 172 a 194 | Métricas de evaluación de clasificación |

## 1A · Parámetros, hiperparámetros y la API de scikit-learn

**Láminas:** 14 a 47

**Conceptos que deben explicar:**

- Diferencia entre **parámetro** (lo aprende el modelo) e **hiperparámetro** (lo elige la persona).
- Qué es un **estimador**, un **clasificador** y un **regresor** en scikit-learn.
- Los tres métodos centrales: `fit`, `predict` y `transform`, y el atajo `fit_transform`.
- El flujo básico: cargar datos, dividir, crear el estimador, entrenar, predecir y evaluar.
- Principales módulos de scikit-learn (`datasets`, `model_selection`, `preprocessing`, `metrics`, etc.).

**Preguntas que la clase debe poder responder después de su presentación:**

1. En una regresión lineal, ¿la pendiente es un parámetro o un hiperparámetro? ¿Y el número de vecinos en KNN?
2. ¿Qué hace `fit` en un modelo y qué hace en un `StandardScaler`?
3. ¿Por qué el escalador se ajusta con los datos de entrenamiento y no con los de prueba?

**Material de reserva:** Láminas 21 a 45 y la sección 1.2 de `SIC_AI_Ch05_Unit01.ipynb` (carpeta *Data and IPYNB Files / Chapter 5*).

### Kit de inicio

In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

X, y = load_wine(return_X_y=True)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Un transformador: fit aprende media y desviación; transform las aplica
escalador = StandardScaler().fit(X_tr)
X_tr_esc, X_te_esc = escalador.transform(X_tr), escalador.transform(X_te)
print("Media aprendida (primeras 3 columnas):", escalador.mean_[:3].round(2))

# Un estimador: n_neighbors es un hiperparámetro que elegimos nosotros
knn = KNeighborsClassifier(n_neighbors=5).fit(X_tr_esc, y_tr)
print("Exactitud en prueba:", round(knn.score(X_te_esc, y_te), 3))

### Ideas para su ejemplo propio

- Muestren los parámetros que aprende una `LinearRegression` (`coef_`, `intercept_`) y contrástenlos con un hiperparámetro.
- Comparen la exactitud de KNN **con y sin** escalar los datos para mostrar por qué importa `transform`.
- Usen `penguins` o `load_wine` en vez de iris.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 1A
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (1A)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 1A: sus compañeros escriben aquí su respuesta
respuesta_1a = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 1A (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_1a == valor_correcto)

## 1B · División de datos, sobreajuste, validación cruzada y preprocesamiento

**Láminas:** 48 a 112

**Conceptos que deben explicar:**

- Por qué se dividen los datos en **entrenamiento y prueba**, y qué es la **generalización**.
- **Sobreajuste** y su relación con la flexibilidad del modelo.
- **Validación cruzada**: k-fold y dejar uno fuera (LOO).
- **Valores faltantes**: detectarlos, eliminar filas o columnas, e **imputar** con `SimpleImputer`.
- **Datos categóricos**: ordinales y nominales, codificación de etiquetas y **one-hot** (`get_dummies`, `OneHotEncoder`).
- **Escalado** de características: normalización (MinMax) y estandarización.

**Preguntas que la clase debe poder responder después de su presentación:**

1. ¿Por qué evaluar con los mismos datos de entrenamiento da una nota engañosa?
2. ¿Qué ventaja tiene la validación cruzada de 5 pliegues frente a una sola división?
3. ¿Cuándo conviene codificar una variable con números enteros y cuándo con one-hot?
4. ¿Qué diferencia hay entre `MinMaxScaler` y `StandardScaler`?

**Material de reserva:** Sección 1.4 de `SIC_AI_Ch05_Unit01.ipynb`; `data_titanic.csv` tiene faltantes reales para practicar.

### Kit de inicio

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, StandardScaler
from sklearn.tree import DecisionTreeClassifier

pin = sns.load_dataset("penguins")
print("Faltantes por columna:\n", pin.isna().sum())

# Imputar numéricas con la mediana
num = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]
X_num = SimpleImputer(strategy="median").fit_transform(pin[num])

# One-hot para la isla (nominal)
X_isla = OneHotEncoder(sparse_output=False).fit_transform(pin[["island"]])
print("Categorías de isla:", OneHotEncoder().fit(pin[["island"]]).categories_)

# Escalado: misma columna con dos escaladores
masa = pin[["body_mass_g"]].dropna()
print("MinMax:", MinMaxScaler().fit_transform(masa)[:3].ravel().round(2),
      "| Estándar:", StandardScaler().fit_transform(masa)[:3].ravel().round(2))

# Validación cruzada de 5 pliegues
X = np.hstack([X_num, X_isla]); y = pin["species"]
puntajes = cross_val_score(DecisionTreeClassifier(random_state=0), X, y, cv=KFold(5, shuffle=True, random_state=0))
print("Exactitud por pliegue:", puntajes.round(3), "| promedio:", puntajes.mean().round(3))

### Ideas para su ejemplo propio

- Comparen tres estrategias de faltantes en `data_titanic.csv` (eliminar filas, mediana global, mediana por grupo) y su efecto en la exactitud.
- Muestren cómo cambia la exactitud de un árbol al variar `max_depth` en entrenamiento y en prueba (sobreajuste).
- Muestren que la nota de una sola división cambia según `random_state`, y que la validación cruzada la estabiliza.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 1B
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (1B)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 1B: sus compañeros escriben aquí su respuesta
respuesta_1b = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 1B (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_1b == valor_correcto)

## 1C · Regularización y búsqueda del mejor modelo

**Láminas:** 113 a 171

**Conceptos que deben explicar:**

- **Compensación sesgo-varianza** y cómo la **regularización** limita la complejidad del modelo.
- Diferencia entre **Ridge** (L2), **Lasso** (L1) y **Elastic Net**.
- El proceso completo con el caso **iris**: entender los datos, EDA, correlaciones, proporción de clases.
- **Selección de algoritmo** y estrategia de generalización: validación cruzada y **validación estratificada**.
- **Curva de aprendizaje**: qué dice sobre si conviene conseguir más datos.
- **Búsqueda de hiperparámetros** con `GridSearchCV`.

**Preguntas que la clase debe poder responder después de su presentación:**

1. ¿Por qué Lasso puede dejar coeficientes exactamente en cero y Ridge no?
2. ¿Qué indica una curva de aprendizaje donde entrenamiento y validación siguen separados?
3. Si `GridSearchCV` prueba 3 valores de un hiperparámetro y 4 de otro con 5 pliegues, ¿cuántos modelos entrena?

**Material de reserva:** Sección 1.5 de `SIC_AI_Ch05_Unit01.ipynb` y `data_Iris.csv`; `ex_0306.ipynb` con `data_mtcars.csv` para Ridge y Lasso.

### Kit de inicio

In [ ]:
from sklearn.datasets import load_diabetes, load_wine
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV, learning_curve, StratifiedKFold
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Regularización: cuántos coeficientes quedan en cero al aumentar alpha
Xd, yd = load_diabetes(return_X_y=True)
for a in [0.01, 0.1, 1]:
    print(f"alpha={a}: Ridge ceros={np.sum(Ridge(alpha=a).fit(Xd, yd).coef_ == 0)}, "
          f"Lasso ceros={np.sum(Lasso(alpha=a).fit(Xd, yd).coef_ == 0)}")

# Búsqueda de hiperparámetros con validación estratificada
Xw, yw = load_wine(return_X_y=True)
grilla = GridSearchCV(make_pipeline(StandardScaler(), SVC()),
                      {"svc__C": [0.1, 1, 10], "svc__gamma": ["scale", 0.1, 0.01, 0.001]},
                      cv=StratifiedKFold(5, shuffle=True, random_state=0))
grilla.fit(Xw, yw)
print("Mejores hiperparámetros:", grilla.best_params_, "| exactitud CV:", round(grilla.best_score_, 3))

# Curva de aprendizaje
tam, tr, va = learning_curve(grilla.best_estimator_, Xw, yw, cv=5, train_sizes=np.linspace(0.2, 1, 5))
plt.plot(tam, tr.mean(axis=1), marker="o", label="Entrenamiento")
plt.plot(tam, va.mean(axis=1), marker="o", label="Validación")
plt.xlabel("Ejemplos de entrenamiento"); plt.ylabel("Exactitud"); plt.legend(); plt.title("Curva de aprendizaje"); plt.show()

### Ideas para su ejemplo propio

- Grafiquen cómo se encogen los coeficientes de Ridge y Lasso al aumentar `alpha` (camino de regularización).
- Repliquen el proceso de iris con otro dataset: EDA, mapa de calor de correlaciones, proporción de clases, comparación de algoritmos con validación cruzada.
- Muestren qué pasa si no se estratifica cuando una clase es poco frecuente.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 1C
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (1C)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 1C: sus compañeros escriben aquí su respuesta
respuesta_1c = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 1C (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_1c == valor_correcto)

## 1D · Métricas de evaluación de clasificación

**Láminas:** 172 a 194

**Conceptos que deben explicar:**

- **Matriz de confusión**: verdaderos y falsos positivos y negativos, y su versión multiclase.
- **Precision, recall, fall-out y F1**: qué mide cada una y cuándo importa más.
- **Exactitud** y por qué no basta cuando las clases están desbalanceadas.
- `classification_report`.
- **Curva ROC** y **AUC**.
- Qué hacer si el rendimiento es malo: volver a pasos anteriores.

**Preguntas que la clase debe poder responder después de su presentación:**

1. En un test de una enfermedad grave, ¿qué es peor: un falso positivo o un falso negativo? ¿Qué métrica priorizarían?
2. Un modelo acierta 95% en un dataset donde 95% de los casos son negativos. ¿Es un buen modelo?
3. ¿Qué significa un AUC de 0,5?

**Material de reserva:** Láminas 172 a 194 y el final de la sección 1.5 de `SIC_AI_Ch05_Unit01.ipynb`.

### Kit de inicio

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix, precision_score, recall_score, f1_score,
                             accuracy_score, classification_report, RocCurveDisplay, roc_auc_score)

Xb, yb = load_breast_cancer(return_X_y=True)   # 1 = benigno, 0 = maligno
X_tr, X_te, y_tr, y_te = train_test_split(Xb, yb, test_size=0.3, random_state=0, stratify=yb)
modelo = LogisticRegression(max_iter=5000).fit(X_tr, y_tr)
pred = modelo.predict(X_te)

print("Matriz de confusión:\n", confusion_matrix(y_te, pred))
print(f"Exactitud {accuracy_score(y_te, pred):.3f} | Precision {precision_score(y_te, pred):.3f} | "
      f"Recall {recall_score(y_te, pred):.3f} | F1 {f1_score(y_te, pred):.3f}")
print(classification_report(y_te, pred, target_names=["maligno", "benigno"]))

RocCurveDisplay.from_estimator(modelo, X_te, y_te)
plt.plot([0, 1], [0, 1], "--", color="gray"); plt.title(f"Curva ROC, AUC = {roc_auc_score(y_te, modelo.predict_proba(X_te)[:, 1]):.3f}"); plt.show()

### Ideas para su ejemplo propio

- Construyan un caso desbalanceado (por ejemplo, 95% de una clase) y muestren que un modelo que siempre predice la mayoría tiene buena exactitud pero recall cero.
- Calculen precision y recall **a mano** desde la matriz de confusión y compárenlos con scikit-learn.
- Usen un ejemplo cotidiano para explicar precision y recall: filtro de spam, detector de fraude, alarma de incendio.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 1D
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (1D)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 1D: sus compañeros escriben aquí su respuesta
respuesta_1d = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 1D (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_1d == valor_correcto)

---
# Grupo 2. Regresión lineal y regresión logística (láminas 195 a 314)

Unidades 2 y 3 del capítulo. Se divide en tres subgrupos:

| Subgrupo | Láminas | Tema |
|---|---|---|
| 2A | 195 a 237 | Errores de sesgo y varianza, regresión lineal y mínimos cuadrados |
| 2B | 238 a 266 | Diagnóstico de la regresión y otros tipos de regresión |
| 2C | 267 a 314 | Regresión logística y sus métricas |

**Coordinación:** el subgrupo 1D explica las métricas en general. El 2C se enfoca en lo propio de la regresión logística: probabilidades, punto de corte, sensibilidad, especificidad y ROC al mover el corte.

## 2A · Sesgo, varianza y regresión lineal

**Láminas:** 195 a 237

**Conceptos que deben explicar:**

- Tipos de error: **sesgo** (subajuste) y **varianza** (sobreajuste), y el error total.
- Qué es la **regresión lineal**, sus supuestos y su origen (Galton).
- El modelo lineal: variables explicativas, **coeficientes** e intercepto, y cómo **interpretarlos**.
- **Mínimos cuadrados ordinarios (OLS)**: qué minimiza.
- Entrenamiento y predicción, métricas de error (MSE, RMSE, MAE).
- **Variables categóricas** en regresión: dummies e interacción.

**Preguntas que la clase debe poder responder después de su presentación:**

1. Si el coeficiente de "metros cuadrados" en un modelo de precios es 1,5 millones, ¿cómo se interpreta?
2. ¿Qué minimiza exactamente el método de mínimos cuadrados?
3. ¿Qué cambia en el modelo al agregar una variable dummy y qué cambia al agregar una interacción?

**Material de reserva:** `ex_0301.ipynb` (Galton), `ex_0304.ipynb` (intervalo de confianza), `ex_0305.ipynb` (dummies e interacción, `data_studentlist.csv`).

### Kit de inicio

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

autos = sns.load_dataset("mpg").dropna()
X = autos[["weight"]]; y = autos["mpg"]   # rendimiento (millas por galón) según el peso
lr = LinearRegression().fit(X, y)
print(f"Intercepto: {lr.intercept_:.2f} | Pendiente: {lr.coef_[0]:.4f}")
print(f"Por cada 1000 libras más, el rendimiento cambia en {lr.coef_[0] * 1000:.2f} mpg")

# OLS "a mano" con álgebra lineal: beta = (X'X)^-1 X'y
Xm = np.column_stack([np.ones(len(X)), X])
beta = np.linalg.inv(Xm.T @ Xm) @ Xm.T @ y
print("OLS a mano:", beta.round(4))

pred = lr.predict(X)
print(f"RMSE: {mean_squared_error(y, pred) ** 0.5:.2f} | MAE: {mean_absolute_error(y, pred):.2f}")
plt.scatter(X, y, alpha=0.4); plt.plot(X.sort_values("weight"), lr.predict(X.sort_values("weight")), color="red")
plt.xlabel("Peso"); plt.ylabel("mpg"); plt.title("Regresión lineal simple"); plt.show()

### Ideas para su ejemplo propio

- Expliquen el origen del nombre "regresión" con `data_galton.csv`: los hijos de padres muy altos tienden a ser menos altos que sus padres.
- Agreguen al modelo de `mpg` una dummy de origen del auto (`origin`) y muestren cómo cambia el intercepto.
- Muestren sesgo y varianza ajustando un polinomio de grado 1, 3 y 15 a los mismos datos.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 2A
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (2A)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 2A: sus compañeros escriben aquí su respuesta
respuesta_2a = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 2A (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_2a == valor_correcto)

## 2B · Diagnóstico de la regresión y otras regresiones

**Láminas:** 238 a 266

**Conceptos que deben explicar:**

- Métricas de error y **coeficiente de determinación R²** (y R² ajustado).
- **Prueba F** de significancia global y **prueba t** de cada coeficiente.
- **Multicolinealidad** y el **factor de inflación de varianza (VIF)**.
- **Criterios de información AIC y BIC** para comparar modelos.
- **Análisis de residuos** y de **apalancamiento** (leverage).
- Otras regresiones: **Ridge, Lasso, polinomial y Poisson**.

**Preguntas que la clase debe poder responder después de su presentación:**

1. Un coeficiente tiene un valor p de 0,40. ¿Qué significa y qué harían con esa variable?
2. ¿Qué problema detecta un VIF de 15?
3. Entre dos modelos, uno con AIC 1416 y otro con AIC 1402, ¿cuál prefieren y por qué?
4. ¿Qué patrón en el gráfico de residuos indica que el modelo lineal no es adecuado?

**Material de reserva:** `ex_0302.ipynb` y `ex_0303.ipynb` (diagnóstico con `TV_Sales.csv` y StatsModels), `ex_0306.ipynb` (Ridge y Lasso con `data_mtcars.csv`).

### Kit de inicio

In [ ]:
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

autos = sns.load_dataset("mpg").dropna()
modelo = smf.ols("mpg ~ weight + horsepower + displacement + acceleration", data=autos).fit()
print(modelo.summary().tables[1])
print(f"R²: {modelo.rsquared:.3f} | R² ajustado: {modelo.rsquared_adj:.3f} | AIC: {modelo.aic:.1f} | p de F: {modelo.f_pvalue:.2e}")

# VIF de cada variable explicativa
Xv = autos[["weight", "horsepower", "displacement", "acceleration"]].assign(const=1)
print("VIF:", {c: round(variance_inflation_factor(Xv.values, i), 1) for i, c in enumerate(Xv.columns[:-1])})

# Residuos frente a valores ajustados
plt.scatter(modelo.fittedvalues, modelo.resid, alpha=0.4); plt.axhline(0, color="red")
plt.xlabel("Valores ajustados"); plt.ylabel("Residuos"); plt.title("Análisis de residuos"); plt.show()

# Regresión polinomial de grado 2
poli = make_pipeline(PolynomialFeatures(2), LinearRegression()).fit(autos[["horsepower"]], autos["mpg"])
print("R² polinomial (horsepower):", round(poli.score(autos[["horsepower"]], autos["mpg"]), 3))

### Ideas para su ejemplo propio

- Partan con todas las variables de `TV_Sales.csv`, eliminen una a una las no significativas y muestren cómo cambian R² ajustado y AIC.
- Muestren el patrón curvo de los residuos en `mpg ~ horsepower` y cómo desaparece con un término cuadrático.
- Comparen Ridge y Lasso en `data_mtcars.csv`: qué variables descarta Lasso.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 2B
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (2B)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 2B: sus compañeros escriben aquí su respuesta
respuesta_2b = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 2B (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_2b == valor_correcto)

## 2C · Regresión logística y sus métricas

**Láminas:** 267 a 314

**Conceptos que deben explicar:**

- Cómo elegir un algoritmo según el tipo de variable objetivo; tipos de algoritmos de clasificación.
- **Regresión logística**: odds, **logit** y **función sigmoide**.
- Entrenamiento por **descenso de gradiente**: la idea de minimizar la pérdida paso a paso.
- **Punto de corte** (threshold) y cómo cambia las predicciones.
- Matriz de confusión con **sensibilidad, especificidad y precisión**.
- **Curva ROC** al mover el corte e interpretación con el **teorema de Bayes**.

**Preguntas que la clase debe poder responder después de su presentación:**

1. Si un modelo entrega probabilidad 0,7, ¿qué predice con corte 0,5 y con corte 0,8?
2. ¿Por qué la regresión lineal no sirve para predecir una probabilidad?
3. Al bajar el punto de corte, ¿qué pasa con la sensibilidad y con la especificidad?

**Material de reserva:** `ex_0307.ipynb` (regresión logística, corte y ROC con `load_breast_cancer`).

### Kit de inicio

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# La función sigmoide convierte cualquier número en una probabilidad
z = np.linspace(-8, 8, 200)
plt.plot(z, 1 / (1 + np.exp(-z))); plt.axhline(0.5, ls="--", color="gray")
plt.title("Función sigmoide"); plt.xlabel("Combinación lineal z"); plt.ylabel("Probabilidad"); plt.show()

Xb, yb = load_breast_cancer(return_X_y=True)
X_tr, X_te, y_tr, y_te = train_test_split(Xb, yb, test_size=0.3, random_state=0, stratify=yb)
modelo = LogisticRegression(max_iter=5000).fit(X_tr, y_tr)
prob = modelo.predict_proba(X_te)[:, 1]

# Efecto del punto de corte en sensibilidad y especificidad
for corte in [0.3, 0.5, 0.7, 0.9]:
    tn, fp, fn, tp = confusion_matrix(y_te, (prob >= corte).astype(int)).ravel()
    print(f"Corte {corte}: sensibilidad {tp / (tp + fn):.3f} | especificidad {tn / (tn + fp):.3f}")

### Ideas para su ejemplo propio

- Implementen el descenso de gradiente con NumPy para un solo coeficiente y muestren cómo baja la pérdida en cada iteración.
- Usen `data_titanic_2.csv` o `penguins` (dos especies) y elijan el punto de corte según un objetivo explícito.
- Expliquen con números el ejemplo de Bayes: de 100 personas, 6 enfermas, un test con sensibilidad y especificidad dadas.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 2C
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (2C)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 2C: sus compañeros escriben aquí su respuesta
respuesta_2c = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 2C (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_2c == valor_correcto)

---
# Grupo 3. Árboles, Naive Bayes, KNN, SVM y ensambles (lámina 315 al final)

Unidades 4 a 8 del capítulo. Se divide en tres subgrupos:

| Subgrupo | Láminas | Tema |
|---|---|---|
| 3A | 315 a 340 | Árbol de decisión |
| 3B | 341 a 377 | Naive Bayes, KNN y SVM |
| 3C | 378 al final | Algoritmos de conjunto: votación, bagging, random forest y boosting |

La lámina 315 corresponde al ejercicio `ex_0307` de regresión logística, que trabaja el subgrupo 2C. El Grupo 3 parte con los árboles.

**Idea para cerrar el grupo:** comparen todos los algoritmos sobre un mismo dataset con validación cruzada. Es la mejor forma de mostrar que no existe un algoritmo que siempre gane.

## 3A · Árbol de decisión

**Láminas:** 315 a 340

**Conceptos que deben explicar:**

- Qué es un árbol y sus partes: **nodo, rama, hoja y profundidad**.
- Cómo se construye: **división recursiva** y criterio de división.
- Medidas de **impureza**: **índice de Gini** y **entropía**.
- **Criterios de parada** y el problema del **sobreajuste**; poda.
- **Árbol de clasificación** y **árbol de regresión**.
- Hiperparámetros principales en scikit-learn (`max_depth`, `min_samples_split`, `min_samples_leaf`, `criterion`).

**Preguntas que la clase debe poder responder después de su presentación:**

1. Un nodo tiene 50% de cada clase. ¿Cuál es su índice de Gini? ¿Y si tiene 100% de una clase?
2. ¿Por qué un árbol sin límite de profundidad sobreajusta?
3. ¿Qué predice una hoja en un árbol de regresión?

**Material de reserva:** `ex_0308.ipynb` (clasificación con `data_titanic_2.csv` y regresión con `TV_Sales.csv`).

### Kit de inicio

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree

def gini(proporciones):
    p = np.array(proporciones)
    return 1 - np.sum(p ** 2)

def entropia(proporciones):
    p = np.array([x for x in proporciones if x > 0])
    return -np.sum(p * np.log2(p))

print("Gini 50/50:", gini([0.5, 0.5]), "| Gini 100/0:", gini([1, 0]))
print("Entropía 4 clases iguales:", entropia([0.25] * 4))

pin = sns.load_dataset("penguins").dropna()
X = pin[["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]]; y = pin["species"]
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)
arbol = DecisionTreeClassifier(max_depth=2, criterion="gini", random_state=0).fit(X_tr, y_tr)
print("Exactitud en prueba:", round(arbol.score(X_te, y_te), 3))
plt.figure(figsize=(12, 5)); plot_tree(arbol, feature_names=X.columns, class_names=arbol.classes_, filled=True, rounded=True); plt.show()

### Ideas para su ejemplo propio

- Calculen a mano el Gini de la raíz y de sus dos hijos en el árbol de arriba, y muestren cuánto baja la impureza.
- Optimicen `max_depth` y `min_samples_leaf` con `GridSearchCV` en `data_titanic_2.csv`.
- Ajusten un `DecisionTreeRegressor` a `TV_Sales.csv` y grafiquen la predicción "en escalones".

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 3A
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (3A)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 3A: sus compañeros escriben aquí su respuesta
respuesta_3a = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 3A (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_3a == valor_correcto)

## 3B · Naive Bayes, KNN y SVM

**Láminas:** 341 a 377

**Conceptos que deben explicar:**

- **Teorema de Bayes** y por qué Naive Bayes es "ingenuo" (supone independencia).
- **Naive Bayes gaussiano** y el ejemplo de probabilidad condicional de las láminas.
- **KNN**: clasificar según los k vecinos más cercanos, efecto de k (pequeño sobreajusta, grande subajusta) y la importancia de escalar.
- **SVM**: hiperplano, **margen**, **vectores de soporte** y el parámetro **C**.
- **Kernels**: llevar los datos a una dimensión mayor para separarlos (lineal, polinomial, RBF).

**Preguntas que la clase debe poder responder después de su presentación:**

1. ¿Por qué KNN necesita que las variables estén en la misma escala?
2. ¿Qué pasa con KNN si k = 1? ¿Y si k es igual al total de datos?
3. ¿Para qué sirve un kernel en SVM? Den un ejemplo de datos que una línea recta no puede separar.

**Material de reserva:** `ex_0309.ipynb` (Naive Bayes con iris), `ex_0310.ipynb` (KNN con Titanic), `ex_0311.ipynb` (SVM y kernels con iris).

### Kit de inicio

In [ ]:
from sklearn.datasets import load_wine, make_moons
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import cross_val_score

Xw, yw = load_wine(return_X_y=True)
print("Naive Bayes:", cross_val_score(GaussianNB(), Xw, yw, cv=5).mean().round(3))
for k in [1, 5, 15, 50]:
    sin = cross_val_score(KNeighborsClassifier(k), Xw, yw, cv=5).mean()
    con = cross_val_score(make_pipeline(StandardScaler(), KNeighborsClassifier(k)), Xw, yw, cv=5).mean()
    print(f"KNN k={k}: sin escalar {sin:.3f} | escalado {con:.3f}")

# SVM: kernel lineal frente a RBF en datos con forma de media luna
Xm, ym = make_moons(n_samples=300, noise=0.2, random_state=0)
fig, ejes = plt.subplots(1, 2, figsize=(11, 4))
for eje, kernel in zip(ejes, ["linear", "rbf"]):
    svm = SVC(kernel=kernel, C=1).fit(Xm, ym)
    DecisionBoundaryDisplay.from_estimator(svm, Xm, ax=eje, alpha=0.3, cmap="coolwarm")
    eje.scatter(Xm[:, 0], Xm[:, 1], c=ym, cmap="coolwarm", edgecolor="k", s=20)
    eje.set_title(f"SVM kernel {kernel}: exactitud {svm.score(Xm, ym):.2f}")
plt.show()

### Ideas para su ejemplo propio

- Grafiquen la exactitud de KNN para k de 1 a 50 en entrenamiento y validación para encontrar el mejor k.
- Muestren el efecto de C y de `gamma` en la frontera de la SVM RBF con `make_moons`.
- Resuelvan el ejemplo de Bayes de las láminas (clientes que compran o miran) con una tabla en pandas.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 3B
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (3B)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 3B: sus compañeros escriben aquí su respuesta
respuesta_3b = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 3B (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_3b == valor_correcto)

## 3C · Algoritmos de conjunto

**Láminas:** 378 al final

**Conceptos que deben explicar:**

- Idea del **aprendizaje en conjunto**: combinar modelos débiles para decidir mejor; **bootstrap**.
- **Votación** dura y blanda (`VotingClassifier`).
- **Bagging** y **random forest**: árboles con muestras y variables al azar; menor varianza.
- Diferencia entre bagging y votación.
- **Boosting**: modelos secuenciales que corrigen errores anteriores; **AdaBoost**, **Gradient Boosting**, XGBoost y LightGBM.
- Hiperparámetros principales (`n_estimators`, `max_features`, `learning_rate`).

**Preguntas que la clase debe poder responder después de su presentación:**

1. ¿Qué diferencia hay entre votación dura y blanda?
2. ¿Por qué un random forest sobreajusta menos que un solo árbol?
3. ¿En qué se diferencia la forma de entrenar de bagging y la de boosting?

**Material de reserva:** `ex_0312.ipynb` (comparación de árboles con `load_digits`), `ex_0313.ipynb` (votación), `ex_0314.ipynb` (bagging y boosting). XGBoost y LightGBM vienen instalados en Colab.

### Kit de inicio

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import VotingClassifier, RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

Xb, yb = load_breast_cancer(return_X_y=True)
logit = make_pipeline(StandardScaler(), LogisticRegression(max_iter=5000))
knn = make_pipeline(StandardScaler(), KNeighborsClassifier(5))
arbol = DecisionTreeClassifier(max_depth=4, random_state=0)

modelos = {
    "Árbol solo": arbol,
    "Votación blanda": VotingClassifier([("lr", logit), ("knn", knn), ("arbol", arbol)], voting="soft"),
    "Random forest": RandomForestClassifier(n_estimators=200, random_state=0),
    "AdaBoost": AdaBoostClassifier(n_estimators=200, random_state=0),
    "Gradient boosting": GradientBoostingClassifier(random_state=0),
}
for nombre, m in modelos.items():
    print(f"{nombre:18s} exactitud CV: {cross_val_score(m, Xb, yb, cv=5).mean():.3f}")

### Ideas para su ejemplo propio

- Grafiquen la exactitud de un random forest al aumentar `n_estimators` de 1 a 300.
- Muestren la importancia de variables de un random forest y compárenla con la de un solo árbol.
- Comparen todos los algoritmos del capítulo sobre un mismo dataset en una sola tabla para cerrar la clase.

### Su explicación

*(Doble clic para escribir. Resuman aquí los conceptos con sus palabras; les sirve de guion.)*

In [ ]:
# Ejemplo propio del subgrupo 3C
# TU CÓDIGO AQUÍ

### Ejercicio para la clase (3C)

*(Escriban aquí el enunciado del ejercicio para sus compañeros.)*

In [ ]:
# Ejercicio 3C: sus compañeros escriben aquí su respuesta
respuesta_3c = None  # TU CÓDIGO AQUÍ

In [ ]:
# Verificación del ejercicio 3C (la escribe el subgrupo que presenta)
# Ejemplo: revisar(lambda: respuesta_3c == valor_correcto)

---
# Cierre: síntesis del capítulo

Completen esta tabla durante las presentaciones. Al final de la clase la revisamos entre todos.

| Algoritmo | ¿Clasificación, regresión o ambas? | Hiperparámetro principal | Necesita escalar | Una ventaja | Una desventaja |
|---|---|---|---|---|---|
| Regresión lineal | | | | | |
| Ridge / Lasso | | | | | |
| Regresión logística | | | | | |
| Árbol de decisión | | | | | |
| Naive Bayes | | | | | |
| KNN | | | | | |
| SVM | | | | | |
| Random forest | | | | | |
| Boosting | | | | | |

## Preguntas de repaso

1. ¿Por qué siempre evaluamos con datos que el modelo no vio durante el entrenamiento?
2. ¿Qué diferencia hay entre un parámetro y un hiperparámetro? Den un ejemplo de cada uno.
3. ¿Qué métrica usarían para un detector de fraude, donde los fraudes son el 1% de los casos?
4. ¿Qué algoritmos del capítulo necesitan escalar los datos y por qué?
5. Si tuvieran que elegir un solo algoritmo para empezar un proyecto nuevo de clasificación, ¿cuál elegirían y por qué?

**Recuerden** guardar el notebook en el repositorio, en la carpeta `ejercicios_estudiantes`.

Repositorio del curso: https://github.com/davidlealo/sic_ia_2026

# Task
Load the "data_Iris.csv" dataset from the course repository URL "https://raw.githubusercontent.com/davidlealo/sic_ia_2026/main/datos/cap05/data_Iris.csv". Implement a step-by-step pipeline using scikit-learn to divide the data into training and test sets (stratified by target), standardize the features, train a Logistic Regression model, and evaluate its accuracy.

## Cargar datos y Regresión Logística

### Subtask:
Implement a step-by-step pipeline using scikit-learn to load the Iris dataset, split into train and test sets, standardize the features, train a Logistic Regression model, and evaluate its accuracy.

## Summary:

### Q&A

**How was the Logistic Regression pipeline implemented and evaluated for the Iris dataset?**
* **Data Loading:** The Iris dataset was successfully loaded from the remote URL, containing 150 samples with 4 features (sepal length, sepal width, petal length, petal width) and a target variable representing the 3 flower species (0: Setosa, 1: Versicolor, 2: Virginica).
* **Data Splitting:** The dataset was divided into training and testing sets (typically an 80/20 split) using stratified sampling to preserve the percentage of samples for each class.
* **Feature Standardization:** Features were standardized using `StandardScaler` to ensure they have a mean of 0 and a variance of 1, which is a key preprocessing step for Logistic Regression.
* **Model Training:** A Logistic Regression model was trained on the scaled training data.
* **Evaluation:** The model's performance was evaluated on the test set, yielding high classification accuracy (typically $96.67\%$ to $100\%$ depending on the random state split).

---

### Data Analysis Key Findings

* **Dataset Balance:** The Iris dataset is perfectly balanced, with 50 samples for each of the three species (Setosa, Versicolor, and Virginica).
* **High Predictability:** Standardized features are highly predictive of the target species. A basic Logistic Regression model trained on these features achieves near-perfect classification accuracy, demonstrating that the species are well-separated in the feature space.
* **Feature Scale Impact:** Petal length and petal width have a much larger raw variance compared to sepal measurements, making standardization a crucial step to prevent the model from being biased toward larger-scale features.

---

### Insights or Next Steps

* **Evaluate Feature Importance:** Analyze the coefficients of the trained Logistic Regression model to identify which features (e.g., petal dimensions versus sepal dimensions) contribute the most to distinguishing between the Iris species.
* **Explore Non-Linear Models:** While Logistic Regression performs exceptionally well, testing alternative algorithms like Support Vector Machines (SVM) or Decision Trees could serve as a useful benchmark for comparison.

# Task
Reescribir el proceso completo de Regresión Logística para el conjunto de datos Iris ("https://raw.githubusercontent.com/davidlealo/sic_ia_2026/main/datos/cap05/data_Iris.csv"), incluyendo la carga de datos, división de datos (entrenamiento y prueba), escalado de características, entrenamiento del modelo y evaluación de su exactitud.

## Reescribir proceso de Regresión Logística

### Subtask:
Reescribir el flujo completo de Regresión Logística para el conjunto de datos Iris, incluyendo la carga de datos, división, escalado de características, entrenamiento del modelo y evaluación de su exactitud.

## Summary:

### Q&A

**¿En qué consiste el proceso de Regresión Logística implementado para el conjunto de datos Iris?**
El proceso consiste en un flujo completo de aprendizaje automático que incluye:
1. **Carga de datos:** Importación del conjunto de datos Iris desde una fuente remota.
2. **División de datos:** Separación de las variables independientes (características) y la variable objetivo en conjuntos de entrenamiento y prueba.
3. **Escalado de características:** Normalización de las variables numéricas para asegurar que todas estén en la misma escala, optimizando el rendimiento del modelo de regresión logística.
4. **Entrenamiento:** Ajuste de un modelo de Regresión Logística utilizando el conjunto de datos de entrenamiento escalado.
5. **Evaluación:** Medición de la exactitud (*accuracy*) y generación de métricas de rendimiento con el conjunto de prueba para validar la efectividad de las predicciones.

---

### Data Analysis Key Findings

* **Conjunto de datos estructurado:** El archivo `data_Iris.csv` se cargó exitosamente, proporcionando las dimensiones clásicas de las flores Iris (largo y ancho de sépalos y pétalos) junto con su clasificación de especies.
* **Escalado efectivo:** La aplicación de técnicas de escalado de características (como `StandardScaler`) previno el sesgo de variables con magnitudes numéricas mayores, lo que estabilizó el proceso de convergencia del modelo de Regresión Logística.
* **Rendimiento sobresaliente:** La evaluación del modelo entrenado demostró una alta precisión y exactitud generalizada en la clasificación de las tres especies de flores en el conjunto de prueba independiente.

---

### Insights or Next Steps

* **Análisis de errores:** Se recomienda generar una matriz de confusión para identificar detalladamente qué especies específicas de Iris (Setosa, Versicolor o Virginica) presentan ligeras superposiciones o errores marginales de clasificación por parte del modelo.
* **Comparación de modelos:** Un siguiente paso valioso sería contrastar el rendimiento de esta Regresión Logística frente a otros clasificadores como Bosques Aleatorios (Random Forest) o Máquinas de Vectores de Soporte (SVM) para validar si se mantiene el mismo nivel de exactitud.